export const rankAllData = [
  {
    rank: 1,
    product: "ChatGPT",
    category: "AI ChatBots",
    visits: 1642000,
    change: "2%",
  },
  {
    rank: 2,
    product: "NewBing",
    category: "",
    visits: 164800,
    change: "3%",
  },
  {
    rank: 3,
    product: "Canva AI",
    category: "绘图设计工具",
    visits: 148700,
    change: "-4%",
  },
  {
    rank: 4,
    product: "Google Gemini",
    category: "AI ChatBots",
    visits: 38800,
    change: "-1%",
  },
  {
    rank: 5,
    product: "Adobe firefly",
    category: "图像生成",
    visits: 20300,
    change: "-6%",
  },
  {
    rank: 6,
    product: "DeepL",
    category: "翻译",
    visits: 26600,
    change: "10%",
  },
  {
    rank: 7,
    product: "Character.AI",
    category: "AI ChatBots",
    visits: 12600,
    change: "2%",
  },
  {
    rank: 8,
    product: "Notion AI",
    category: "通用写作",
    visits: 9250,
    change: "-2%",
  },
  {
    rank: 9,
    product: "ChatGPT",
    category: "AI ChatBots",
    visits: 6400,
    change: "-7%",
  },
  {
    rank: 10,
    product: "IShop",
    category: "虚拟陪伴",
    visits: 8800,
    change: "-2%",
  },
  {
    rank: 11,
    product: "Top Tech",
    category: "垂直行业",
    visits: 8824,
    change: "2%",
  },
  {
    rank: 12,
    product: "figma+jamboard",
    category: "图像编辑",
    visits: 8557,
    change: "2%",
  },
  {
    rank: 13,
    product: "Salesforce",
    category: "",
    visits: 8754,
    change: "2%",
  },
  {
    rank: 14,
    product: "Pimeyes",
    category: "",
    visits: 7834,
    change: "0%",
  },
  {
    rank: 15,
    product: "ChatPDF",
    category: "AI ChatBots",
    visits: 7664,
    change: "8%",
  },
  {
    rank: 16,
    product: "Papercup AI",
    category: "图生视频",
    visits: 7408,
    change: "-2%",
  },
  {
    rank: 17,
    product: "ChatPDF",
    category: "AI ChatBots",
    visits: 7664,
    change: "8%",
  },
  {
    rank: 18,
    product: "Studioxrock",
    category: "图像生成",
    visits: 6674,
    change: "-4%",
  },
  {
    rank: 19,
    product: "Skill AI",
    category: "AI ChatBots",
    visits: 6240,
    change: "0%",
  },
  {
    rank: 20,
    product: "LINER AI",
    category: "",
    visits: 5900,
    change: "2%",
  },
  {
    rank: 21,
    product: "ReImagine",
    category: "",
    visits: 5377,
    change: "-7%",
  },
  {
    rank: 22,
    product: "Ontraport",
    category: "",
    visits: 5250,
    change: "-3%",
  },
  {
    rank: 23,
    product: "Poe",
    category: "AI ChatBots",
    visits: 4974,
    change: "4%",
  },
  {
    rank: 24,
    product: "kmeringo",
    category: "AI ChatBots",
    visits: 4896,
    change: "5%",
  },
  {
    rank: 25,
    product: "DeepChat AI",
    category: "AI ChatBots",
    visits: 4624,
    change: "2%",
  },
  {
    rank: 26,
    product: "SpicyChat.AI",
    category: "AI ChatBots",
    visits: 4278,
    change: "5%",
  },
  {
    rank: 27,
    product: "GPT3 Playground",
    category: "AI ChatBots",
    visits: 4216,
    change: "-7%",
  },
  {
    rank: 28,
    product: "figma+jamboard",
    category: "图像编辑",
    visits: 3828,
    change: "2%",
  },
  {
    rank: 29,
    product: "Hopscotch",
    category: "",
    visits: 2896,
    change: "7%",
  },
  {
    rank: 30,
    product: "Cvat.ai",
    category: "",
    visits: 2380,
    change: "1%",
  },
  {
    rank: 31,
    product: "Beacoms AI 2.0",
    category: "AI ChatBots",
    visits: 2117,
    change: "0%",
  },
  {
    rank: 32,
    product: "SpicyChat.AI",
    category: "AI ChatBots",
    visits: 2077,
    change: "5%",
  },
  {
    rank: 33,
    product: "Reeni",
    category: "",
    visits: 2017,
    change: "0%",
  },
  {
    rank: 34,
    product: "Bifrost Labs",
    category: "",
    visits: 1899,
    change: "1%",
  },
  {
    rank: 35,
    product: "KarmaKorner.ai",
    category: "AI ChatBots",
    visits: 1839,
    change: "5%",
  },
  {
    rank: 36,
    product: "Flowrite",
    category: "AI ChatBots",
    visits: 1798,
    change: "-2%",
  },
  {
    rank: 37,
    product: "mailchimp",
    category: "邮件助手",
    visits: 1747,
    change: "-2%",
  },
  {
    rank: 38,
    product: "Replai",
    category: "",
    visits: 1748,
    change: "-6%",
  },
  {
    rank: 39,
    product: "MidJourney",
    category: "图像生成",
    visits: 1709,
    change: "0%",
  },
  {
    rank: 40,
    product: "Lessexx AI",
    category: "AI ChatBots",
    visits: 1643,
    change: "-4%",
  },
  {
    rank: 41,
    product: "Cushion",
    category: "视频编辑",
    visits: 1683,
    change: "1%",
  },
  {
    rank: 42,
    product: "Gptforresearch.com",
    category: "AI ChatBots",
    visits: 1660,
    change: "0%",
  },
  {
    rank: 43,
    product: "Cutout.pro",
    category: "图像生成",
    visits: 1620,
    change: "2%",
  },
  {
    rank: 44,
    product: "Yeduo",
    category: "",
    visits: 1590,
    change: "-5%",
  },
  {
    rank: 45,
    product: "Fotor",
    category: "",
    visits: 1577,
    change: "-2%",
  },
  {
    rank: 46,
    product: "Bifi",
    category: "",
    visits: 1460,
    change: "0%",
  },
  {
    rank: 47,
    product: "ssuiteos.com",
    category: "",
    visits: 1473,
    change: "2%",
  },
  {
    rank: 48,
    product: "Lensica AI",
    category: "",
    visits: 1420,
    change: "1%",
  },
  {
    rank: 49,
    product: "Wendu AI",
    category: "AI ChatBots",
    visits: 1380,
    change: "0%",
  },
  {
    rank: 50,
    product: "Replit",
    category: "编程工具",
    visits: 1220,
    change: "1%",
  },
  {
    rank: 51,
    product: "Looka.com",
    category: "",
    visits: 1210,
    change: "1%",
  },
  {
    rank: 52,
    product: "Picuio.com",
    category: "",
    visits: 1173,
    change: "1%",
  },
  {
    rank: 53,
    product: "Slidego",
    category: "",
    visits: 1120,
    change: "-4%",
  },
  {
    rank: 54,
    product: "Sidepop",
    category: "",
    visits: 1074,
    change: "1%",
  },
  {
    rank: 55,
    product: "RoboFlow",
    category: "AI ChatBots",
    visits: 1065,
    change: "2%",
  },
  {
    rank: 56,
    product: "gfg",
    category: "AI ChatBots",
    visits: 1034,
    change: "2%",
  },
  {
    rank: 57,
    product: "ZeroGPT",
    category: "AI ChatBots",
    visits: 1032,
    change: "4%",
  },
  {
    rank: 58,
    product: "Spacehally",
    category: "AI ChatBots",
    visits: 1020,
    change: "0%",
  },
  {
    rank: 59,
    product: "DeepAi",
    category: "AI ChatBots",
    visits: 1013,
    change: "1%",
  },
  {
    rank: 60,
    product: "WembaAI",
    category: "",
    visits: 1009,
    change: "6%",
  },
  {
    rank: 61,
    product: "SatChat AI",
    category: "AI ChatBots",
    visits: 1002,
    change: "-5%",
  },
  {
    rank: 62,
    product: "GC Spark",
    category: "",
    visits: 987,
    change: "-7%",
  },
  {
    rank: 63,
    product: "PLAN by Indigo",
    category: "AI ChatBots",
    visits: 942,
    change: "-2%",
  },
  {
    rank: 64,
    product: "Replai",
    category: "",
    visits: 918,
    change: "1%",
  },
  {
    rank: 65,
    product: "Semantic Scholar",
    category: "",
    visits: 917,
    change: "-7%",
  },
  {
    rank: 66,
    product: "Replai",
    category: "",
    visits: 879,
    change: "-4%",
  },
  {
    rank: 67,
    product: "Semantic Scholar",
    category: "",
    visits: 860,
    change: "-7%",
  },
  {
    rank: 68,
    product: "Pitch",
    category: "",
    visits: 842,
    change: "1%",
  },
  {
    rank: 69,
    product: "Storypitchgenius.com",
    category: "",
    visits: 816,
    change: "-2%",
  },
  {
    rank: 70,
    product: "Ideaopra.com",
    category: "",
    visits: 806,
    change: "1%",
  },
  {
    rank: 71,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 794,
    change: "-4%",
  },
  {
    rank: 72,
    product: "PoeChat AI",
    category: "AI ChatBots",
    visits: 789,
    change: "-5%",
  },
  {
    rank: 73,
    product: "Ideaopra.com",
    category: "",
    visits: 778,
    change: "-12%",
  },
  {
    rank: 74,
    product: "PDFCoCo",
    category: "AI ChatBots",
    visits: 749,
    change: "1%",
  },
  {
    rank: 75,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 744,
    change: "0%",
  },
  {
    rank: 76,
    product: "Replit",
    category: "编程工具",
    visits: 719,
    change: "-2%",
  },
  {
    rank: 77,
    product: "Spacehally",
    category: "AI ChatBots",
    visits: 702,
    change: "0%",
  },
  {
    rank: 78,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 677,
    change: "1%",
  },
  {
    rank: 79,
    product: "Replit",
    category: "编程工具",
    visits: 671,
    change: "-7%",
  },
  {
    rank: 80,
    product: "Slidego",
    category: "",
    visits: 662,
    change: "1%",
  },
  {
    rank: 81,
    product: "Semantic Scholar",
    category: "",
    visits: 641,
    change: "-4%",
  },
  {
    rank: 82,
    product: "Pitch",
    category: "",
    visits: 624,
    change: "1%",
  },
  {
    rank: 83,
    product: "Storypitchgenius.com",
    category: "",
    visits: 610,
    change: "-6%",
  },
  {
    rank: 84,
    product: "Ideaopra.com",
    category: "",
    visits: 589,
    change: "-3%",
  },
  {
    rank: 85,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 576,
    change: "-6%",
  },
  {
    rank: 86,
    product: "PoeChat AI",
    category: "AI ChatBots",
    visits: 562,
    change: "1%",
  },
  {
    rank: 87,
    product: "Ideaopra.com",
    category: "",
    visits: 554,
    change: "0%",
  },
  {
    rank: 88,
    product: "PDFCoCo",
    category: "AI ChatBots",
    visits: 544,
    change: "1%",
  },
  {
    rank: 89,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 531,
    change: "-7%",
  },
  {
    rank: 90,
    product: "Replit",
    category: "编程工具",
    visits: 512,
    change: "-2%",
  },
  {
    rank: 91,
    product: "Replit",
    category: "编程工具",
    visits: 497,
    change: "-4%",
  },
  {
    rank: 92,
    product: "Semantic Scholar",
    category: "",
    visits: 479,
    change: "-2%",
  },
  {
    rank: 93,
    product: "Pitch",
    category: "",
    visits: 460,
    change: "1%",
  },
  {
    rank: 94,
    product: "Ideaopra.com",
    category: "",
    visits: 448,
    change: "-5%",
  },
  {
    rank: 95,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 437,
    change: "1%",
  },
  {
    rank: 96,
    product: "PoeChat AI",
    category: "AI ChatBots",
    visits: 423,
    change: "0%",
  },
  {
    rank: 97,
    product: "Ideaopra.com",
    category: "",
    visits: 410,
    change: "0%",
  },
  {
    rank: 98,
    product: "PDFCoCo",
    category: "AI ChatBots",
    visits: 398,
    change: "0%",
  },
  {
    rank: 99,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 387,
    change: "-1%",
  },
  {
    rank: 100,
    product: "Ideaopra.com",
    category: "",
    visits: 370,
    change: "0%",
  },
]

export const chinaAiProductTop50 = [
  {
    rank: 1,
    product: "百度文心 AI 功能",
    category: "AI Writer Generator",
    visits: "65.36M",
    change: "71.18%",
  },
  {
    rank: 2,
    product: "360AI 搜索",
    category: "AI Search Engine",
    visits: "50.98M",
    change: "332.79%",
  },
  {
    rank: 3,
    product: "Kimi（月之暗面）",
    category: "AI ChatBots",
    visits: "23.03M",
    change: "258.56%",
  },
  {
    rank: 4,
    product: "百度文心一言",
    category: "AI ChatBots",
    visits: "19.84M",
    change: "230.46%",
  },
  {
    rank: 5,
    product: "天工 AI（配音秀）",
    category: "AI ChatBots",
    visits: "17.21M",
    change: "332.44%",
  },
  {
    rank: 6,
    product: "秘塔 AI 搜索",
    category: "AI Search Engine",
    visits: "14.50M",
    change: "36.97%",
  },
  {
    rank: 7,
    product: "阿里 AI 文问答",
    category: "AI ChatBots",
    visits: "8.14M",
    change: "31.77%",
  },
  {
    rank: 8,
    product: "抖音云图",
    category: "AI ChatBots",
    visits: "5.35M",
    change: "30.04%",
  },
  {
    rank: 9,
    product: "Ai PPT.cn",
    category: "AI Presentation Maker",
    visits: "4.54M",
    change: "90.86%",
  },
  {
    rank: 10,
    product: "洋葱研究所",
    category: "AI ChatBots",
    visits: "4.00M",
    change: "10.09%",
  },
  {
    rank: 11,
    product: "火山引擎",
    category: "Model Training & Deployment",
    visits: "3.68M",
    change: "17.63%",
  },
  {
    rank: 12,
    product: "美图设计大师",
    category: "AI Design Tool",
    visits: "3.23M",
    change: "27.78%",
  },
  {
    rank: 13,
    product: "腾讯云智能客服",
    category: "AI ChatBots",
    visits: "2.49M",
    change: "188.05%",
  },
  {
    rank: 14,
    product: "Coze",
    category: "AI ChatBots",
    visits: "2.49M",
    change: "189.05%",
  },
  {
    rank: 15,
    product: "liblib.art",
    category: "Model Training & Deployment",
    visits: "2.42M",
    change: "188.60%",
  },
  {
    rank: 16,
    product: "ProcessOn",
    category: "AI Mind Map Generator",
    visits: "2.29M",
    change: "2.27%",
  },
  {
    rank: 17,
    product: "魔音工坊",
    category: "AI Audio Editing Tools",
    visits: "2.20M",
    change: "-1.00%",
  },
  {
    rank: 18,
    product: "腾讯文档翻译",
    category: "AI Translate Tools",
    visits: "2.02M",
    change: "1.01%",
  },
  {
    rank: 19,
    product: "墨刀 AI",
    category: "AI Design Tool",
    visits: "1.90M",
    change: "28.35%",
  },
  {
    rank: 20,
    product: "像素 AI",
    category: "AI Video Generators",
    visits: "1.74M",
    change: "19.66%",
  },
  {
    rank: 21,
    product: "无限画",
    category: "AI Image Generator",
    visits: "1.54M",
    change: "16.98%",
  },
  {
    rank: 22,
    product: "同花顺问财",
    category: "AI Finance",
    visits: "1.53M",
    change: "3.33%",
  },
  {
    rank: 23,
    product: "即时 AI",
    category: "AI Design Tool",
    visits: "1.19M",
    change: "28.35%",
  },
  {
    rank: 24,
    product: "MasterGo AI",
    category: "AI Design Tool",
    visits: "1.12M",
    change: "-3.55%",
  },
  {
    rank: 25,
    product: "ai-bot",
    category: "AI navigation site",
    visits: "1.06M",
    change: "-5.82%",
  },
  {
    rank: 26,
    product: "百度文心",
    category: "AI ChatBots",
    visits: "1.04M",
    change: "-14.77%",
  },
  {
    rank: 27,
    product: "创客 AI",
    category: "AI Design Tool",
    visits: "1.01M",
    change: "-3.15%",
  },
  {
    rank: 28,
    product: "腾讯数据广场",
    category: "Model Training & Deployment",
    visits: "994.91K",
    change: "-0.07%",
  },
  {
    rank: 29,
    product: "提示工程指南",
    category: "AI Prompt Generator",
    visits: "912.99K",
    change: "10.57%",
  },
  {
    rank: 30,
    product: "博思 AI 幻灯片",
    category: "AI Presentation Maker",
    visits: "891.38K",
    change: "0.73%",
  },
  {
    rank: 31,
    product: "海棠 AI",
    category: "AI ChatBots",
    visits: "830.54K",
    change: "44.02%",
  },
  {
    rank: 32,
    product: "树莓派助手",
    category: "AI Writer Generator",
    visits: "732.02K",
    change: "2.45%",
  },
  {
    rank: 33,
    product: "杨小树 Logo 生成",
    category: "AI Image Generator",
    visits: "675.22K",
    change: "-5.01%",
  },
  {
    rank: 34,
    product: "讯飞听见",
    category: "AI Transcription Software",
    visits: "647.8K",
    change: "13.48%",
  },
  {
    rank: 35,
    product: "360 番茄办公",
    category: "Productivity",
    visits: "615.77K",
    change: "21.38%",
  },
  {
    rank: 36,
    product: "亿图脑图",
    category: "AI Mind Map Generator",
    visits: "606.12K",
    change: "6.49%",
  },
  {
    rank: 37,
    product: "Pixso AI",
    category: "AI Design Tool",
    visits: "600.02K",
    change: "6.44%",
  },
  {
    rank: 38,
    product: "5118 SEO 优化精灵",
    category: "AI Writer Generator",
    visits: "521.81K",
    change: "-23.77%",
  },
  {
    rank: 39,
    product: "百度文心智能",
    category: "AI ChatBots",
    visits: "518.26K",
    change: "-14.73%",
  },
  {
    rank: 40,
    product: "devv.ai",
    category: "AI Search Engine",
    visits: "508.01K",
    change: "-0.42%",
  },
  {
    rank: 41,
    product: "百度文心一格",
    category: "AI Image Generator",
    visits: "464.18K",
    change: "-2.65%",
  },
  {
    rank: 42,
    product: "佐糖",
    category: "AI Image Editor",
    visits: "426.02K",
    change: "-1.63%",
  },
  {
    rank: 43,
    product: "阿里道义听悟",
    category: "Productivity",
    visits: "420.82K",
    change: "-16.27%",
  },
  {
    rank: 44,
    product: "笔灵 AI 写作",
    category: "AI Writer Generator",
    visits: "378.2K",
    change: "-6.21%",
  },
  {
    rank: 45,
    product: "象鼻 AI",
    category: "AI Writer Generator",
    visits: "377.71K",
    change: "11.57%",
  },
  {
    rank: 46,
    product: "昇思 MindSpore",
    category: "AI Code Assistant",
    visits: "363.38K",
    change: "-1.98%",
  },
  {
    rank: 47,
    product: "网易云翻译",
    category: "AI Translate Tools",
    visits: "357.69K",
    change: "-2.31%",
  },
  {
    rank: 48,
    product: "腾讯智影",
    category: "AI Video Editing",
    visits: "355.35K",
    change: "-2.04%",
  },
  {
    rank: 49,
    product: "涂鸦",
    category: "AI ChatBots",
    visits: "336.77K",
    change: "1391.39%",
  },
  {
    rank: 50,
    product: "万向",
    category: "AI ChatBots",
    visits: "336.77K",
    change: "1391.39%",
  },
]

export const a16zTopWebAI = [
  {
    rank: 1,
    product: "ChatGPT",
    link: "https://chat.openai.com/",
  },
  {
    rank: 2,
    product: "Gemini",
    link: "https://gemini.google.com/",
  },
  {
    rank: 3,
    product: "Character.AI",
    link: "https://beta.character.ai/",
  },
  {
    rank: 4,
    product: "Liner",
    link: "https://getliner.com/",
  },
  {
    rank: 5,
    product: "QuillBot",
    link: "http://quillbot.com",
  },
  {
    rank: 6,
    product: "Poe",
    link: "http://poe.com/",
  },
  {
    rank: 7,
    product: "Perplexity",
    link: "https://www.perplexity.ai/",
  },
  {
    rank: 8,
    product: "JanitorAI",
    link: "http://janitorai.com/",
  },
  {
    rank: 9,
    product: "Civitai",
    link: "http://civitai.com",
  },
  {
    rank: 10,
    product: "Claude",
    link: "https://claude.ai/",
  },
  {
    rank: 11,
    product: "ElevenLabs",
    link: "https://elevenlabs.io/",
  },
  {
    rank: 12,
    product: "Hugging Face",
    link: "https://huggingface.co/",
  },
  {
    rank: 13,
    product: "Leonardo.AI",
    link: "http://leonardo.ai/",
  },
  {
    rank: 14,
    product: "Midjourney",
    link: "http://midjourney.com",
  },
  {
    rank: 15,
    product: "SpicyChat",
    link: "http://spicychat.ai/",
  },
  {
    rank: 16,
    product: "Gamma",
    link: "https://gamma.app/",
  },
  {
    rank: 17,
    product: "CrushOn AI",
    link: "http://crushon.ai/",
  },
  {
    rank: 18,
    product: "Cutout.pro",
    link: "https://www.cutout.pro/",
  },
  {
    rank: 19,
    product: "Pixlr",
    link: "http://pixlr.com",
  },
  {
    rank: 20,
    product: "Veed.io",
    link: "https://www.veed.io/",
  },
  {
    rank: 21,
    product: "PhotoRoom",
    link: "http://photoroom.com/",
  },
  {
    rank: 22,
    product: "Yodayo",
    link: "http://yodayo.com/",
  },
  {
    rank: 23,
    product: "Clipchamp",
    link: "http://clipchamp.com/",
  },
  {
    rank: 24,
    product: "Runway",
    link: "http://runwayml.com",
  },
  {
    rank: 25,
    product: "You.com",
    link: "https://you.com/",
  },
  {
    rank: 26,
    product: "DeepAI",
    link: "http://deepai.org/",
  },
  {
    rank: 27,
    product: "Eightify",
    link: "https://eightify.app/",
  },
  {
    rank: 28,
    product: "Candy.ai",
    link: "https://candy.ai/",
  },
  {
    rank: 29,
    product: "NightCafe",
    link: "https://creator.nightcafe.studio/",
  },
  {
    rank: 30,
    product: "VocalRemover",
    link: "https://vocalremover.org/",
  },
  {
    rank: 31,
    product: "Pixai",
    link: "https://pixai.art/",
  },
  {
    rank: 32,
    product: "Ideogram",
    link: "http://ideogram.ai/",
  },
  {
    rank: 33,
    product: "InVideo",
    link: "http://invideo.io/",
  },
  {
    rank: 34,
    product: "Replicate",
    link: "https://replicate.com/",
  },
  {
    rank: 35,
    product: "Playground",
    link: "http://playgroundai.com/",
  },
  {
    rank: 36,
    product: "Suno",
    link: "https://www.suno.ai/",
  },
  {
    rank: 37,
    product: "Chub.ai",
    link: "http://chub.ai/",
  },
  {
    rank: 38,
    product: "Speechify",
    link: "http://speechify.com/",
  },
  {
    rank: 39,
    product: "Phind",
    link: "http://phind.com/",
  },
  {
    rank: 40,
    product: "NovelAI",
    link: "http://novelai.net/",
  },
  {
    rank: 41,
    product: "MaxAI",
    link: "http://maxai.me/",
  },
  {
    rank: 42,
    product: "Craiyon",
    link: "http://craiyon.com/",
  },
  {
    rank: 43,
    product: "OpusClip",
    link: "http://opus.pro",
  },
  {
    rank: 44,
    product: "Blackbox AI",
    link: "https://www.blackbox.ai/",
  },
  {
    rank: 45,
    product: "ChatPDF",
    link: "https://www.chatpdf.com/",
  },
  {
    rank: 46,
    product: "Pixelcut",
    link: "http://pixelcut.ai/",
  },
  {
    rank: 47,
    product: "Vectorizer.AI",
    link: "https://vectorizer.ai/",
  },
  {
    rank: 48,
    product: "DreamGF",
    link: "https://dreamgf.ai/",
  },
  {
    rank: 49,
    product: "Photomyne",
    link: "https://photomyne.com/",
  },
  {
    rank: 50,
    product: "Otter.ai",
    link: "http://otter.ai/",
  },
]

export const a16zTopAppAI = [
  {
    rank: 1,
    product: "ChatGPT",
    link: "https://apps.apple.com/us/app/chatgpt/id6448311069",
  },
  {
    rank: 2,
    product: "Microsoft Edge",
    link: "https://apps.apple.com/us/app/microsoft-edge-ai-browser/id1288723196",
  },
  {
    rank: 3,
    product: "Photomath",
    link: "https://apps.apple.com/us/app/photomath/id919087726",
  },
  {
    rank: 4,
    product: "Bing",
    link: "https://apps.apple.com/us/app/bing-chat-with-ai-gpt-4/id345323231",
  },
  {
    rank: 5,
    product: "Remini",
    link: "https://apps.apple.com/us/app/remini-ai-photo-enhancer/id1470373330",
  },
  {
    rank: 6,
    product: "Brainly",
    link: "https://apps.apple.com/us/app/brainly-ai-homework-helper/id745089947",
  },
  {
    rank: 7,
    product: "NOVA",
    link: "https://apps.apple.com/us/app/ai-chatbot-nova/id1669007652",
  },
  {
    rank: 8,
    product: "Chat & Ask AI",
    link: "https://apps.apple.com/us/app/chat-ask-ai-by-codeway/id1668787639",
  },
  {
    rank: 9,
    product: "Facemoji",
    link: "https://apps.apple.com/us/app/facemoji-ai-emoji-keyboard/id1103138272",
  },
  {
    rank: 10,
    product: "EPIK",
    link: "https://apps.apple.com/us/app/epik-ai-photo-video-editor/id1577705074",
  },
  {
    rank: 11,
    product: "Photoroom",
    link: "https://apps.apple.com/us/app/photoroom-ai-photo-editor/id1455009060",
  },
  {
    rank: 12,
    product: "Remove It",
    link: "https://play.google.com/store/apps/details?id=com.vyroai.objectremover&hl=en_US",
  },
  {
    rank: 13,
    product: "Evoke AI",
    link: "https://apps.apple.com/us/app/ai-photo-enhancer-evoke/id6450504740",
  },
  {
    rank: 14,
    product: "AI Chatbot: AI Chat Smith 4",
    link: "https://apps.apple.com/us/app/ai-chatbot-ai-chat-smith-4/id1559479889",
  },
  {
    rank: 15,
    product: "ChatBot",
    link: "https://chatbot-ai-chat.en.softonic.com/",
  },
  {
    rank: 16,
    product: "character.ai",
    link: "https://apps.apple.com/us/app/character-ai-ai-powered-chat/id1671705818",
  },
  {
    rank: 17,
    product: "AI Mirror",
    link: "https://apps.apple.com/us/app/ai-mirror-ai-art-photo-editor/id6444888896",
  },
  {
    rank: 18,
    product: "ChatOn",
    link: "https://apps.apple.com/us/app/chaton-ai-chat-bot-assistant/id1661308505",
  },
  {
    rank: 19,
    product: "QANDA",
    link: "https://apps.apple.com/us/app/qanda-instant-math-helper/id1270676408",
  },
  {
    rank: 20,
    product: "Face Dance",
    link: "https://apps.apple.com/us/app/face-dance-ai-photo-animator/id1589749730",
  },
  {
    rank: 21,
    product: "Beat.ly",
    link: "https://play.google.com/store/apps/details?id=vinkle.video.editor",
  },
  {
    rank: 22,
    product: "Photo AI",
    link: "https://apps.apple.com/us/app/photoai-ai-photo-enhancer/id1590124720",
  },
  {
    rank: 23,
    product: "Hypic",
    link: "https://apps.apple.com/us/app/hypic-photo-editor-ai-art/id1644042837",
  },
  {
    rank: 24,
    product: "Al Quran",
    link: "https://apps.apple.com/us/app/al-quran-tafsir-by-word/id1437038111",
  },
  {
    rank: 25,
    product: "ArtMind",
    link: "https://apps.apple.com/us/app/artmind/id6477348273",
  },
  {
    rank: 26,
    product: "SnapEdit",
    link: "https://play.google.com/store/apps/details?id=snapedit.app.remove",
  },
  {
    rank: 27,
    product: "Imagine",
    link: "https://apps.apple.com/us/app/imagine-ai-art-generator/id1664121419",
  },
  {
    rank: 28,
    product: "Question AI",
    link: "https://apps.apple.com/us/app/question-ai-ai-math-calculator/id6449486871",
  },
  {
    rank: 29,
    product: "ChatBox",
    link: "https://apps.apple.com/us/app/chatbox-ask-ai-chatbot/id6447763703",
  },
  {
    rank: 30,
    product: "DaVinci",
    link: "https://apps.apple.com/us/app/davinci-ai-image-generator/id1630366866",
  },
  {
    rank: 31,
    product: "Bobble AI",
    link: "https://apps.apple.com/us/app/bobble-ai-keyboard-assistant/id972432964",
  },
  {
    rank: 32,
    product: "reface",
    link: "https://apps.apple.com/us/app/reface-ai-photo-generator/id1488782587?ppid=eb3a176a-5e0e-42f2-99f5-78428b29eace",
  },
  {
    rank: 33,
    product: "PhotoApp",
    link: "https://apps.apple.com/us/app/photoapp-ai-photo-enhancer/id1596089614",
  },
  {
    rank: 34,
    product: "Prequel",
    link: "https://apps.apple.com/us/app/prequel-photo-video-editor/id1325756279",
  },
  {
    rank: 35,
    product: "Mathway",
    link: "https://apps.apple.com/us/app/mathway-math-problem-solver/id467329677",
  },
  {
    rank: 36,
    product: "Poly.AI",
    link: "https://apps.apple.com/us/app/poly-ai-create-ai-chat-bot/id6449190344",
  },
  {
    rank: 37,
    product: "Genie",
    link: "https://apps.apple.com/us/app/genie-ai-chatbot-keyboard/id1658377526",
  },
  {
    rank: 38,
    product: "Photoleap",
    link: "https://apps.apple.com/us/app/photoleap-ai-art-photo-editor/id1191337894",
  },
  {
    rank: 39,
    product: "Wonder",
    link: "https://apps.apple.com/us/app/wonder-ai-art-generator/id1621278575",
  },
  {
    rank: 40,
    product: "Copilot",
    link: "https://apps.apple.com/us/app/microsoft-copilot/id6472538445",
  },
  {
    rank: 41,
    product: "Chat AI",
    link: "https://play.google.com/store/apps/details?id=com.ai.chat.bot.aichat",
  },
  {
    rank: 42,
    product: "ELSA",
    link: "https://apps.apple.com/us/app/elsa-speak-english-learning/id1083804886",
  },
  {
    rank: 43,
    product: "AI ARTA",
    link: "https://apps.apple.com/us/app/arta-ai-photo-generator-al-art/id1642969698",
  },
  {
    rank: 44,
    product: "AI Chat",
    link: "https://apps.apple.com/us/app/ai-chat-assistant-chatbot/id1667518571",
  },
  {
    rank: 45,
    product: "Revive",
    link: "https://apps.apple.com/us/app/revive-ai-photo-dance-maker/id1616862692",
  },
  {
    rank: 46,
    product: "LISA AI",
    link: "https://apps.apple.com/us/app/lisa-ai-retro-wedding-avatar/id6443832829",
  },
  {
    rank: 47,
    product: "PIXELCUT",
    link: "https://apps.apple.com/us/app/pixelcut-ai-photo-editor/id1534785237",
  },
  {
    rank: 48,
    product: "AI Chat - Assistant",
    link: "https://apps.apple.com/us/app/ai-chat-assistant-chatbot/id1667518571",
  },
  {
    rank: 49,
    product: "Poe",
    link: "https://apps.apple.com/us/app/poe-fast-ai-chat/id1640745955",
  },
  {
    rank: 50,
    product: "Replika",
    link: "https://apps.apple.com/us/app/replika-my-ai-friend/id1158555867",
  },
]
