export const rankAllData = [
  {
    rank: 1,
    product: "ChatGPT",
    category: "AI ChatBots",
    visits: 1642000,
    change: "2%",
  },
  {
    rank: 2,
    product: "NewBing",
    category: "",
    visits: 164800,
    change: "3%",
  },
  {
    rank: 3,
    product: "Canva AI",
    category: "绘图设计工具",
    visits: 148700,
    change: "-4%",
  },
  {
    rank: 4,
    product: "Google Gemini",
    category: "AI ChatBots",
    visits: 38800,
    change: "-1%",
  },
  {
    rank: 5,
    product: "Adobe firefly",
    category: "图像生成",
    visits: 20300,
    change: "-6%",
  },
  {
    rank: 6,
    product: "DeepL",
    category: "翻译",
    visits: 26600,
    change: "10%",
  },
  {
    rank: 7,
    product: "Character.AI",
    category: "AI ChatBots",
    visits: 12600,
    change: "2%",
  },
  {
    rank: 8,
    product: "Notion AI",
    category: "通用写作",
    visits: 9250,
    change: "-2%",
  },
  {
    rank: 9,
    product: "ChatGPT",
    category: "AI ChatBots",
    visits: 6400,
    change: "-7%",
  },
  {
    rank: 10,
    product: "IShop",
    category: "虚拟陪伴",
    visits: 8800,
    change: "-2%",
  },
  {
    rank: 11,
    product: "Top Tech",
    category: "垂直行业",
    visits: 8824,
    change: "2%",
  },
  {
    rank: 12,
    product: "figma+jamboard",
    category: "图像编辑",
    visits: 8557,
    change: "2%",
  },
  {
    rank: 13,
    product: "Salesforce",
    category: "",
    visits: 8754,
    change: "2%",
  },
  {
    rank: 14,
    product: "Pimeyes",
    category: "",
    visits: 7834,
    change: "0%",
  },
  {
    rank: 15,
    product: "ChatPDF",
    category: "AI ChatBots",
    visits: 7664,
    change: "8%",
  },
  {
    rank: 16,
    product: "Papercup AI",
    category: "图生视频",
    visits: 7408,
    change: "-2%",
  },
  {
    rank: 17,
    product: "ChatPDF",
    category: "AI ChatBots",
    visits: 7664,
    change: "8%",
  },
  {
    rank: 18,
    product: "Studioxrock",
    category: "图像生成",
    visits: 6674,
    change: "-4%",
  },
  {
    rank: 19,
    product: "Skill AI",
    category: "AI ChatBots",
    visits: 6240,
    change: "0%",
  },
  {
    rank: 20,
    product: "LINER AI",
    category: "",
    visits: 5900,
    change: "2%",
  },
  {
    rank: 21,
    product: "ReImagine",
    category: "",
    visits: 5377,
    change: "-7%",
  },
  {
    rank: 22,
    product: "Ontraport",
    category: "",
    visits: 5250,
    change: "-3%",
  },
  {
    rank: 23,
    product: "Poe",
    category: "AI ChatBots",
    visits: 4974,
    change: "4%",
  },
  {
    rank: 24,
    product: "kmeringo",
    category: "AI ChatBots",
    visits: 4896,
    change: "5%",
  },
  {
    rank: 25,
    product: "DeepChat AI",
    category: "AI ChatBots",
    visits: 4624,
    change: "2%",
  },
  {
    rank: 26,
    product: "SpicyChat.AI",
    category: "AI ChatBots",
    visits: 4278,
    change: "5%",
  },
  {
    rank: 27,
    product: "GPT3 Playground",
    category: "AI ChatBots",
    visits: 4216,
    change: "-7%",
  },
  {
    rank: 28,
    product: "figma+jamboard",
    category: "图像编辑",
    visits: 3828,
    change: "2%",
  },
  {
    rank: 29,
    product: "Hopscotch",
    category: "",
    visits: 2896,
    change: "7%",
  },
  {
    rank: 30,
    product: "Cvat.ai",
    category: "",
    visits: 2380,
    change: "1%",
  },
  {
    rank: 31,
    product: "Beacoms AI 2.0",
    category: "AI ChatBots",
    visits: 2117,
    change: "0%",
  },
  {
    rank: 32,
    product: "SpicyChat.AI",
    category: "AI ChatBots",
    visits: 2077,
    change: "5%",
  },
  {
    rank: 33,
    product: "Reeni",
    category: "",
    visits: 2017,
    change: "0%",
  },
  {
    rank: 34,
    product: "Bifrost Labs",
    category: "",
    visits: 1899,
    change: "1%",
  },
  {
    rank: 35,
    product: "KarmaKorner.ai",
    category: "AI ChatBots",
    visits: 1839,
    change: "5%",
  },
  {
    rank: 36,
    product: "Flowrite",
    category: "AI ChatBots",
    visits: 1798,
    change: "-2%",
  },
  {
    rank: 37,
    product: "mailchimp",
    category: "邮件助手",
    visits: 1747,
    change: "-2%",
  },
  {
    rank: 38,
    product: "Replai",
    category: "",
    visits: 1748,
    change: "-6%",
  },
  {
    rank: 39,
    product: "MidJourney",
    category: "图像生成",
    visits: 1709,
    change: "0%",
  },
  {
    rank: 40,
    product: "Lessexx AI",
    category: "AI ChatBots",
    visits: 1643,
    change: "-4%",
  },
  {
    rank: 41,
    product: "Cushion",
    category: "视频编辑",
    visits: 1683,
    change: "1%",
  },
  {
    rank: 42,
    product: "Gptforresearch.com",
    category: "AI ChatBots",
    visits: 1660,
    change: "0%",
  },
  {
    rank: 43,
    product: "Cutout.pro",
    category: "图像生成",
    visits: 1620,
    change: "2%",
  },
  {
    rank: 44,
    product: "Yeduo",
    category: "",
    visits: 1590,
    change: "-5%",
  },
  {
    rank: 45,
    product: "Fotor",
    category: "",
    visits: 1577,
    change: "-2%",
  },
  {
    rank: 46,
    product: "Bifi",
    category: "",
    visits: 1460,
    change: "0%",
  },
  {
    rank: 47,
    product: "ssuiteos.com",
    category: "",
    visits: 1473,
    change: "2%",
  },
  {
    rank: 48,
    product: "Lensica AI",
    category: "",
    visits: 1420,
    change: "1%",
  },
  {
    rank: 49,
    product: "Wendu AI",
    category: "AI ChatBots",
    visits: 1380,
    change: "0%",
  },
  {
    rank: 50,
    product: "Replit",
    category: "编程工具",
    visits: 1220,
    change: "1%",
  },
  {
    rank: 51,
    product: "Looka.com",
    category: "",
    visits: 1210,
    change: "1%",
  },
  {
    rank: 52,
    product: "Picuio.com",
    category: "",
    visits: 1173,
    change: "1%",
  },
  {
    rank: 53,
    product: "Slidego",
    category: "",
    visits: 1120,
    change: "-4%",
  },
  {
    rank: 54,
    product: "Sidepop",
    category: "",
    visits: 1074,
    change: "1%",
  },
  {
    rank: 55,
    product: "RoboFlow",
    category: "AI ChatBots",
    visits: 1065,
    change: "2%",
  },
  {
    rank: 56,
    product: "gfg",
    category: "AI ChatBots",
    visits: 1034,
    change: "2%",
  },
  {
    rank: 57,
    product: "ZeroGPT",
    category: "AI ChatBots",
    visits: 1032,
    change: "4%",
  },
  {
    rank: 58,
    product: "Spacehally",
    category: "AI ChatBots",
    visits: 1020,
    change: "0%",
  },
  {
    rank: 59,
    product: "DeepAi",
    category: "AI ChatBots",
    visits: 1013,
    change: "1%",
  },
  {
    rank: 60,
    product: "WembaAI",
    category: "",
    visits: 1009,
    change: "6%",
  },
  {
    rank: 61,
    product: "SatChat AI",
    category: "AI ChatBots",
    visits: 1002,
    change: "-5%",
  },
  {
    rank: 62,
    product: "GC Spark",
    category: "",
    visits: 987,
    change: "-7%",
  },
  {
    rank: 63,
    product: "PLAN by Indigo",
    category: "AI ChatBots",
    visits: 942,
    change: "-2%",
  },
  {
    rank: 64,
    product: "Replai",
    category: "",
    visits: 918,
    change: "1%",
  },
  {
    rank: 65,
    product: "Semantic Scholar",
    category: "",
    visits: 917,
    change: "-7%",
  },
  {
    rank: 66,
    product: "Replai",
    category: "",
    visits: 879,
    change: "-4%",
  },
  {
    rank: 67,
    product: "Semantic Scholar",
    category: "",
    visits: 860,
    change: "-7%",
  },
  {
    rank: 68,
    product: "Pitch",
    category: "",
    visits: 842,
    change: "1%",
  },
  {
    rank: 69,
    product: "Storypitchgenius.com",
    category: "",
    visits: 816,
    change: "-2%",
  },
  {
    rank: 70,
    product: "Ideaopra.com",
    category: "",
    visits: 806,
    change: "1%",
  },
  {
    rank: 71,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 794,
    change: "-4%",
  },
  {
    rank: 72,
    product: "PoeChat AI",
    category: "AI ChatBots",
    visits: 789,
    change: "-5%",
  },
  {
    rank: 73,
    product: "Ideaopra.com",
    category: "",
    visits: 778,
    change: "-12%",
  },
  {
    rank: 74,
    product: "PDFCoCo",
    category: "AI ChatBots",
    visits: 749,
    change: "1%",
  },
  {
    rank: 75,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 744,
    change: "0%",
  },
  {
    rank: 76,
    product: "Replit",
    category: "编程工具",
    visits: 719,
    change: "-2%",
  },
  {
    rank: 77,
    product: "Spacehally",
    category: "AI ChatBots",
    visits: 702,
    change: "0%",
  },
  {
    rank: 78,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 677,
    change: "1%",
  },
  {
    rank: 79,
    product: "Replit",
    category: "编程工具",
    visits: 671,
    change: "-7%",
  },
  {
    rank: 80,
    product: "Slidego",
    category: "",
    visits: 662,
    change: "1%",
  },
  {
    rank: 81,
    product: "Semantic Scholar",
    category: "",
    visits: 641,
    change: "-4%",
  },
  {
    rank: 82,
    product: "Pitch",
    category: "",
    visits: 624,
    change: "1%",
  },
  {
    rank: 83,
    product: "Storypitchgenius.com",
    category: "",
    visits: 610,
    change: "-6%",
  },
  {
    rank: 84,
    product: "Ideaopra.com",
    category: "",
    visits: 589,
    change: "-3%",
  },
  {
    rank: 85,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 576,
    change: "-6%",
  },
  {
    rank: 86,
    product: "PoeChat AI",
    category: "AI ChatBots",
    visits: 562,
    change: "1%",
  },
  {
    rank: 87,
    product: "Ideaopra.com",
    category: "",
    visits: 554,
    change: "0%",
  },
  {
    rank: 88,
    product: "PDFCoCo",
    category: "AI ChatBots",
    visits: 544,
    change: "1%",
  },
  {
    rank: 89,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 531,
    change: "-7%",
  },
  {
    rank: 90,
    product: "Replit",
    category: "编程工具",
    visits: 512,
    change: "-2%",
  },
  {
    rank: 91,
    product: "Replit",
    category: "编程工具",
    visits: 497,
    change: "-4%",
  },
  {
    rank: 92,
    product: "Semantic Scholar",
    category: "",
    visits: 479,
    change: "-2%",
  },
  {
    rank: 93,
    product: "Pitch",
    category: "",
    visits: 460,
    change: "1%",
  },
  {
    rank: 94,
    product: "Ideaopra.com",
    category: "",
    visits: 448,
    change: "-5%",
  },
  {
    rank: 95,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 437,
    change: "1%",
  },
  {
    rank: 96,
    product: "PoeChat AI",
    category: "AI ChatBots",
    visits: 423,
    change: "0%",
  },
  {
    rank: 97,
    product: "Ideaopra.com",
    category: "",
    visits: 410,
    change: "0%",
  },
  {
    rank: 98,
    product: "PDFCoCo",
    category: "AI ChatBots",
    visits: 398,
    change: "0%",
  },
  {
    rank: 99,
    product: "Pin Novel",
    category: "AI ChatBots",
    visits: 387,
    change: "-1%",
  },
  {
    rank: 100,
    product: "Ideaopra.com",
    category: "",
    visits: 370,
    change: "0%",
  },
]

export const chinaAiProductTop50 = [
  {
    rank: 1,
    product: "百度文心 AI 功能",
    category: "AI Writer Generator",
    visits: "65.36M",
    change: "71.18%",
  },
  {
    rank: 2,
    product: "360AI 搜索",
    category: "AI Search Engine",
    visits: "50.98M",
    change: "332.79%",
  },
  {
    rank: 3,
    product: "Kimi（月之暗面）",
    category: "AI ChatBots",
    visits: "23.03M",
    change: "258.56%",
  },
  {
    rank: 4,
    product: "百度文心一言",
    category: "AI ChatBots",
    visits: "19.84M",
    change: "230.46%",
  },
  {
    rank: 5,
    product: "天工 AI（配音秀）",
    category: "AI ChatBots",
    visits: "17.21M",
    change: "332.44%",
  },
  {
    rank: 6,
    product: "秘塔 AI 搜索",
    category: "AI Search Engine",
    visits: "14.50M",
    change: "36.97%",
  },
  {
    rank: 7,
    product: "阿里 AI 文问答",
    category: "AI ChatBots",
    visits: "8.14M",
    change: "31.77%",
  },
  {
    rank: 8,
    product: "抖音云图",
    category: "AI ChatBots",
    visits: "5.35M",
    change: "30.04%",
  },
  {
    rank: 9,
    product: "Ai PPT.cn",
    category: "AI Presentation Maker",
    visits: "4.54M",
    change: "90.86%",
  },
  {
    rank: 10,
    product: "洋葱研究所",
    category: "AI ChatBots",
    visits: "4.00M",
    change: "10.09%",
  },
  {
    rank: 11,
    product: "火山引擎",
    category: "Model Training & Deployment",
    visits: "3.68M",
    change: "17.63%",
  },
  {
    rank: 12,
    product: "美图设计大师",
    category: "AI Design Tool",
    visits: "3.23M",
    change: "27.78%",
  },
  {
    rank: 13,
    product: "腾讯云智能客服",
    category: "AI ChatBots",
    visits: "2.49M",
    change: "188.05%",
  },
  {
    rank: 14,
    product: "Coze",
    category: "AI ChatBots",
    visits: "2.49M",
    change: "189.05%",
  },
  {
    rank: 15,
    product: "liblib.art",
    category: "Model Training & Deployment",
    visits: "2.42M",
    change: "188.60%",
  },
  {
    rank: 16,
    product: "ProcessOn",
    category: "AI Mind Map Generator",
    visits: "2.29M",
    change: "2.27%",
  },
  {
    rank: 17,
    product: "魔音工坊",
    category: "AI Audio Editing Tools",
    visits: "2.20M",
    change: "-1.00%",
  },
  {
    rank: 18,
    product: "腾讯文档翻译",
    category: "AI Translate Tools",
    visits: "2.02M",
    change: "1.01%",
  },
  {
    rank: 19,
    product: "墨刀 AI",
    category: "AI Design Tool",
    visits: "1.90M",
    change: "28.35%",
  },
  {
    rank: 20,
    product: "像素 AI",
    category: "AI Video Generators",
    visits: "1.74M",
    change: "19.66%",
  },
  {
    rank: 21,
    product: "无限画",
    category: "AI Image Generator",
    visits: "1.54M",
    change: "16.98%",
  },
  {
    rank: 22,
    product: "同花顺问财",
    category: "AI Finance",
    visits: "1.53M",
    change: "3.33%",
  },
  {
    rank: 23,
    product: "即时 AI",
    category: "AI Design Tool",
    visits: "1.19M",
    change: "28.35%",
  },
  {
    rank: 24,
    product: "MasterGo AI",
    category: "AI Design Tool",
    visits: "1.12M",
    change: "-3.55%",
  },
  {
    rank: 25,
    product: "ai-bot",
    category: "AI navigation site",
    visits: "1.06M",
    change: "-5.82%",
  },
  {
    rank: 26,
    product: "百度文心",
    category: "AI ChatBots",
    visits: "1.04M",
    change: "-14.77%",
  },
  {
    rank: 27,
    product: "创客 AI",
    category: "AI Design Tool",
    visits: "1.01M",
    change: "-3.15%",
  },
  {
    rank: 28,
    product: "腾讯数据广场",
    category: "Model Training & Deployment",
    visits: "994.91K",
    change: "-0.07%",
  },
  {
    rank: 29,
    product: "提示工程指南",
    category: "AI Prompt Generator",
    visits: "912.99K",
    change: "10.57%",
  },
  {
    rank: 30,
    product: "博思 AI 幻灯片",
    category: "AI Presentation Maker",
    visits: "891.38K",
    change: "0.73%",
  },
  {
    rank: 31,
    product: "海棠 AI",
    category: "AI ChatBots",
    visits: "830.54K",
    change: "44.02%",
  },
  {
    rank: 32,
    product: "树莓派助手",
    category: "AI Writer Generator",
    visits: "732.02K",
    change: "2.45%",
  },
  {
    rank: 33,
    product: "杨小树 Logo 生成",
    category: "AI Image Generator",
    visits: "675.22K",
    change: "-5.01%",
  },
  {
    rank: 34,
    product: "讯飞听见",
    category: "AI Transcription Software",
    visits: "647.8K",
    change: "13.48%",
  },
  {
    rank: 35,
    product: "360 番茄办公",
    category: "Productivity",
    visits: "615.77K",
    change: "21.38%",
  },
  {
    rank: 36,
    product: "亿图脑图",
    category: "AI Mind Map Generator",
    visits: "606.12K",
    change: "6.49%",
  },
  {
    rank: 37,
    product: "Pixso AI",
    category: "AI Design Tool",
    visits: "600.02K",
    change: "6.44%",
  },
  {
    rank: 38,
    product: "5118 SEO 优化精灵",
    category: "AI Writer Generator",
    visits: "521.81K",
    change: "-23.77%",
  },
  {
    rank: 39,
    product: "百度文心智能",
    category: "AI ChatBots",
    visits: "518.26K",
    change: "-14.73%",
  },
  {
    rank: 40,
    product: "devv.ai",
    category: "AI Search Engine",
    visits: "508.01K",
    change: "-0.42%",
  },
  {
    rank: 41,
    product: "百度文心一格",
    category: "AI Image Generator",
    visits: "464.18K",
    change: "-2.65%",
  },
  {
    rank: 42,
    product: "佐糖",
    category: "AI Image Editor",
    visits: "426.02K",
    change: "-1.63%",
  },
  {
    rank: 43,
    product: "阿里道义听悟",
    category: "Productivity",
    visits: "420.82K",
    change: "-16.27%",
  },
  {
    rank: 44,
    product: "笔灵 AI 写作",
    category: "AI Writer Generator",
    visits: "378.2K",
    change: "-6.21%",
  },
  {
    rank: 45,
    product: "象鼻 AI",
    category: "AI Writer Generator",
    visits: "377.71K",
    change: "11.57%",
  },
  {
    rank: 46,
    product: "昇思 MindSpore",
    category: "AI Code Assistant",
    visits: "363.38K",
    change: "-1.98%",
  },
  {
    rank: 47,
    product: "网易云翻译",
    category: "AI Translate Tools",
    visits: "357.69K",
    change: "-2.31%",
  },
  {
    rank: 48,
    product: "腾讯智影",
    category: "AI Video Editing",
    visits: "355.35K",
    change: "-2.04%",
  },
  {
    rank: 49,
    product: "涂鸦",
    category: "AI ChatBots",
    visits: "336.77K",
    change: "1391.39%",
  },
  {
    rank: 50,
    product: "万向",
    category: "AI ChatBots",
    visits: "336.77K",
    change: "1391.39%",
  },
]

export const globalAiAPPProductTop100202406 = [
  {
    rank: 1,
    product: "ChatGPT",
    category: "Productivity",
    visits: "26.47M",
    change: "4.17%",
  },
  {
    rank: 2,
    product: "Remini",
    category: "Photo & Video",
    visits: "15.19M",
    change: "-26.32%",
  },
  {
    rank: 3,
    product: "Canva",
    category: "Photo & Video",
    visits: "13M",
    change: "-14.29%",
  },
  {
    rank: 4,
    product: "豆包(字节)",
    category: "Productivity",
    visits: "9.8M",
    change: "200.00%",
  },
  {
    rank: 5,
    product: "InShot",
    category: "Photo & Video",
    visits: "9.28M",
    change: "",
  },
  {
    rank: 6,
    product: "Bing",
    category: "Productivity",
    visits: "6.97M",
    change: "42.22%",
  },
  {
    rank: 7,
    product: "PhotoRoom",
    category: "Graphics & Design",
    visits: "6.5M",
    change: "50.00%",
  },
  {
    rank: 8,
    product: "Microsoft Edge",
    category: "Tools",
    visits: "5.49M",
    change: "",
  },
  {
    rank: 9,
    product: "Opera",
    category: "Tools",
    visits: "4.89M",
    change: "-2.17%",
  },
  {
    rank: 10,
    product: "Lightroom",
    category: "Photo & Video",
    visits: "4.18M",
    change: "",
  },
  {
    rank: 11,
    product: "FaceApp",
    category: "Photo & Video",
    visits: "3.2M",
    change: "",
  },
  {
    rank: 12,
    product: "Hypic",
    category: "Photo & Video",
    visits: "3.12M",
    change: "",
  },
  {
    rank: 13,
    product: "Character Al",
    category: "Entertainment",
    visits: "2.92M",
    change: "100.00%",
  },
  {
    rank: 14,
    product: "BeautyPlus",
    category: "Photo & Video",
    visits: "2.79M",
    change: "-3.70%",
  },
  {
    rank: 15,
    product: "Linky(昆仑万维)",
    category: "Social Networking",
    visits: "2.71M",
    change: "127.27%",
  },
  {
    rank: 16,
    product: "Facemoji",
    category: "Tools",
    visits: "2.54M",
    change: "",
  },
  {
    rank: 17,
    product: "Filmora",
    category: "Photo & Video",
    visits: "2.54M",
    change: "4.35%",
  },
  {
    rank: 18,
    product: "Brainly",
    category: "Education",
    visits: "2.41M",
    change: "-34.29%",
  },
  {
    rank: 19,
    product: "ChatOn",
    category: "Productivity",
    visits: "2.07M",
    change: "5.26%",
  },
  {
    rank: 20,
    product: "Shop",
    category: "Shopping",
    visits: "1.71M",
    change: "",
  },
  {
    rank: 21,
    product: "Facetune",
    category: "Photo & Video",
    visits: "1.62M",
    change: "7.14%",
  },
  {
    rank: 22,
    product: "Gauthmath",
    category: "Education",
    visits: "1.54M",
    change: "-65.00%",
  },
  {
    rank: 23,
    product: "Talkie (MiniMax)",
    category: "Entertainment",
    visits: "1.47M",
    change: "-39.13%",
  },
  {
    rank: 24,
    product: "Question.Al",
    category: "Education",
    visits: "1.39M",
    change: "-31.58%",
  },
  {
    rank: 25,
    product: "B612",
    category: "Photo & Video",
    visits: "1.38M",
    change: "",
  },
  {
    rank: 26,
    product: "FaceLab",
    category: "Photo & Video",
    visits: "1.33M",
    change: "",
  },
  {
    rank: 27,
    product: "Notion",
    category: "Productivity",
    visits: "1.32M",
    change: "71.43%",
  },
  {
    rank: 28,
    product: "InStories Reels & Stor",
    category: "Photo & Video",
    visits: "1.29M",
    change: "71.43%",
  },
  {
    rank: 29,
    product: "AirBrush",
    category: "Photo & Video",
    visits: "1.26M",
    change: "",
  },
  {
    rank: 30,
    product: "Poly.Al (1)",
    category: "Entertainment",
    visits: "1.19M",
    change: "22.22%",
  },
  {
    rank: 31,
    product: "ΕΡΙΚ",
    category: "Photo & Video",
    visits: "1.14M",
    change: "10.00%",
  },
  {
    rank: 32,
    product: "Cici(字节)",
    category: "Entertainment",
    visits: "1.13M",
    change: "-1.85%",
  },
  {
    rank: 33,
    product: "Prequel",
    category: "Photo & Video",
    visits: "1.1M",
    change: "150.00%",
  },
  {
    rank: 34,
    product: "ChatBox",
    category: "Productivity",
    visits: "1.09M",
    change: "-16.67%",
  },
  {
    rank: 35,
    product: "Nerd Al",
    category: "Education",
    visits: "1.09M",
    change: "-1.00%",
  },
  {
    rank: 36,
    product: "SNOW",
    category: "Photo & Video",
    visits: "1.08M",
    change: "-16.67%",
  },
  {
    rank: 37,
    product: "Face Dance",
    category: "Photo & Video",
    visits: "1.07M",
    change: "",
  },
  {
    rank: 38,
    product: "Wink",
    category: "Photo & Video",
    visits: "1.06M",
    change: "-50.00%",
  },
  {
    rank: 39,
    product: "DeepL Translate",
    category: "Productivity",
    visits: "1.05M",
    change: "-16.67%",
  },
  {
    rank: 40,
    product: "YouCam Makeup",
    category: "Photo & Video",
    visits: "990.25K",
    change: "-10.00%",
  },
  {
    rank: 41,
    product: "文心一言(百度)",
    category: "Productivity",
    visits: "944.45K",
    change: "",
  },
  {
    rank: 42,
    product: "Nova",
    category: "Productivity",
    visits: "878.19K",
    change: "33.33%",
  },
  {
    rank: 43,
    product: "AnyDoor(字节)",
    category: "Entertainment",
    visits: "865.08K",
    change: "101.25%",
  },
  {
    rank: 44,
    product: "Perplexity",
    category: "Productivity",
    visits: "827.92K",
    change: "-11.11%",
  },
  {
    rank: 45,
    product: "Grammarly",
    category: "Productivity",
    visits: "744.34K",
    change: "",
  },
  {
    rank: 46,
    product: "Photoleap",
    category: "Photo & Video",
    visits: "725.71K",
    change: "",
  },
  {
    rank: 47,
    product: "Videoleap",
    category: "Photo & Video",
    visits: "716.87K",
    change: "-12.50%",
  },
  {
    rank: 48,
    product: "Al Chat Chatbot Al A",
    category: "Productivity",
    visits: "658.59K",
    change: "-14.29%",
  },
  {
    rank: 49,
    product: "Pixelcut",
    category: "Graphics & Design",
    visits: "648.85K",
    change: "100.00%",
  },
  {
    rank: 50,
    product: "Reface",
    category: "Photo & Video",
    visits: "550.86K",
    change: "25.00%",
  },
  {
    rank: 51,
    product: "PhotoDirector",
    category: "Photo & Video",
    visits: "546.87K",
    change: "-16.67%",
  },
  {
    rank: 52,
    product: "Kimi(月之暗面)",
    category: "Productivity",
    visits: "542.22K",
    change: "",
  },
  {
    rank: 53,
    product: "Picsify",
    category: "Photo & Video",
    visits: "534.49K",
    change: "25.00%",
  },
  {
    rank: 54,
    product: "Codeway",
    category: "Productivity",
    visits: "528.5K",
    change: "-16.67%",
  },
  {
    rank: 55,
    product: "星野(MiniMax)",
    category: "Social Networking",
    visits: "527.65K",
    change: "25.00%",
  },
  {
    rank: 56,
    product: "Al Chatbot: Chat Ask",
    category: "Productivity",
    visits: "520.95K",
    change: "",
  },
  {
    rank: 57,
    product: "Peachy",
    category: "Photo & Video",
    visits: "516.34K",
    change: "25.00%",
  },
  {
    rank: 58,
    product: "Quizlet",
    category: "Education",
    visits: "512.48K",
    change: "",
  },
  {
    rank: 59,
    product: "Fotor",
    category: "Photo & Video",
    visits: "440.54K",
    change: "",
  },
  {
    rank: 60,
    product: "Naver Papago",
    category: "Reference",
    visits: "437.27K",
    change: "-20.00%",
  },
  {
    rank: 61,
    product: "Wonder",
    category: "Graphics & Design",
    visits: "430.63K",
    change: "-20.00%",
  },
  {
    rank: 62,
    product: "通义千问(阿里)",
    category: "Productivity",
    visits: "430.61K",
    change: "",
  },
  {
    rank: 63,
    product: "Fotor",
    category: "Photo & Video",
    visits: "425.74K",
    change: "",
  },
  {
    rank: 64,
    product: "Genie - Al Chatbot",
    category: "Productivity",
    visits: "424.9K",
    change: "60.00%",
  },
  {
    rank: 65,
    product: "讯飞星火",
    category: "Productivity",
    visits: "412.58K",
    change: "",
  },
  {
    rank: 66,
    product: "Luma Al",
    category: "Photography",
    visits: "405.43K",
    change: "",
  },
  {
    rank: 67,
    product: "QuillBot",
    category: "Productivity",
    visits: "382.55K",
    change: "",
  },
  {
    rank: 68,
    product: "Poe",
    category: "Productivity",
    visits: "329.05K",
    change: "-25.00%",
  },
  {
    rank: 69,
    product: "Object Removal Al Ret",
    category: "Graphics & Design",
    visits: "320.6K",
    change: "",
  },
  {
    rank: 70,
    product: "Poe",
    category: "Productivity",
    visits: "319.92K",
    change: "-25.00%",
  },
  {
    rank: 71,
    product: "Banger",
    category: "Music",
    visits: "319.61K",
    change: "50.00%",
  },
  {
    rank: 72,
    product: "天工Al(昆仑万维)",
    category: "Productivity",
    visits: "318.37K",
    change: "",
  },
  {
    rank: 73,
    product: "Bible Chat",
    category: "Reference",
    visits: "315.27K",
    change: "",
  },
  {
    rank: 74,
    product: "DaVinci",
    category: "Graphics & Design",
    visits: "308.69K",
    change: "-40.00%",
  },
  {
    rank: 75,
    product: "Speechify",
    category: "Magazines & Newspapers",
    visits: "257.55K",
    change: "150.00%",
  },
  {
    rank: 76,
    product: "Zeemo",
    category: "Photo & Video",
    visits: "226.36K",
    change: "",
  },
  {
    rank: 77,
    product: "Photo Eraser - Remov",
    category: "Photo & Video",
    visits: "214.35K",
    change: "100.00%",
  },
  {
    rank: 78,
    product: "光速写作(作业帮)",
    category: "Utilities",
    visits: "212.7K",
    change: "",
  },
  {
    rank: 79,
    product: "Al Chat - Assistant &",
    category: "Productivity",
    visits: "211.02K",
    change: "",
  },
  {
    rank: 80,
    product: "Stemz: Al Tool for Mus",
    category: "Music",
    visits: "210.83K",
    change: "185.71%",
  },
  {
    rank: 81,
    product: "djay",
    category: "Music",
    visits: "210.81K",
    change: "",
  },
  {
    rank: 82,
    product: "OnSkin",
    category: "Health & Fitness",
    visits: "210.15K",
    change: "",
  },
  {
    rank: 83,
    product: "智谱清言",
    category: "Productivity",
    visits: "209.53K",
    change: "",
  },
  {
    rank: 84,
    product: "AI (MiniMax)",
    category: "Productivity",
    visits: "209.38K",
    change: "",
  },
  {
    rank: 85,
    product: "Al Chatbot App with C",
    category: "Productivity",
    visits: "208.6K",
    change: "-33.33%",
  },
  {
    rank: 86,
    product: "TalkAl练口语",
    category: "Education",
    visits: "207.41K",
    change: "100.00%",
  },
  {
    rank: 87,
    product: "Al ChatBot: Smart Ass",
    category: "Productivity",
    visits: "206.16K",
    change: "-33.33%",
  },
  {
    rank: 88,
    product: "Gencraft",
    category: "Graphics & Design",
    visits: "206.02K",
    change: "",
  },
  {
    rank: 89,
    product: "remove.bg",
    category: "Photography",
    visits: "205.42K",
    change: "",
  },
  {
    rank: 90,
    product: "佐糖",
    category: "Graphics & Design",
    visits: "180.53K",
    change: "",
  },
  {
    rank: 91,
    product: "Al Cover & Songs: Mu",
    category: "Music",
    visits: "172.17K",
    change: "-46.67%",
  },
  {
    rank: 92,
    product: "GIO",
    category: "Photo & Video",
    visits: "161.5K",
    change: "-6.25%",
  },
  {
    rank: 93,
    product: "Salesforce",
    category: "Business",
    visits: "146.62K",
    change: "-12.50%",
  },
  {
    rank: 94,
    product: "Replit",
    category: "Developer Tools",
    visits: "142.63K",
    change: "333.33%",
  },
  {
    rank: 95,
    product: "Pixlr",
    category: "Photo & Video",
    visits: "131.45K",
    change: "",
  },
  {
    rank: 96,
    product: "FacePlay",
    category: "Photo & Video",
    visits: "131.27K",
    change: "-20.00%",
  },
  {
    rank: 97,
    product: "Forma",
    category: "Tools",
    visits: "110.05K",
    change: "",
  },
  {
    rank: 98,
    product: "Fotorama",
    category: "Photo & Video",
    visits: "109.94K",
    change: "",
  },
  {
    rank: 99,
    product: "Plantum",
    category: "Education",
    visits: "109.74K",
    change: "-66.67%",
  },
  {
    rank: 100,
    product: "Buddy.ai: Early Learnir",
    category: "Education",
    visits: "109.19K",
    change: "-50.00%",
  },
]

export const globalAiProductTop100202406 = [
  {
    rank: 1,
    product: "ChatGPT",
    category: "Al ChatBots",
    visits: "2.95B",
    change: "14.87%",
  },
  {
    rank: 2,
    product: "New Bing",
    category: "Al Search Engine",
    visits: "1.36B",
    change: "-5.67%",
  },
  {
    rank: 3,
    product: "Canva Text to Image",
    category: "Al Design Tool",
    visits: "584.28M",
    change: "-12.82%",
  },
  {
    rank: 4,
    product: "Character Al",
    category: "Al Character Generat",
    visits: "356.38M",
    change: "13.83%",
  },
  {
    rank: 5,
    product: "Gemini",
    category: "Al ChatBots",
    visits: "352.31M",
    change: "-19.06%",
  },
  {
    rank: 6,
    product: "Deepl",
    category: "Al Translate Tools",
    visits: "266.15M",
    change: "-8.41%",
  },
  {
    rank: 7,
    product: "Notion Al",
    category: "Al Writer Generator",
    visits: "161.95M",
    change: "-5.16%",
  },
  {
    rank: 8,
    product: "Shop",
    category: "E-COMMERCE",
    visits: "104.98M",
    change: "-4.55%",
  },
  {
    rank: 9,
    product: "Jambot",
    category: "Productivity",
    visits: "92.77M",
    change: "-2.93%",
  },
  {
    rank: 10,
    product: "Salesforce Al",
    category: "Al Customer Support",
    visits: "88.29M",
    change: "-1.65%",
  },
  {
    rank: 11,
    product: "Q-Chat",
    category: "Al Tools for Education",
    visits: "87.36M",
    change: "-30.24%",
  },
  {
    rank: 12,
    product: "Perplexity Al",
    category: "Al Search Engine",
    visits: "83.77M",
    change: "-6.22%",
  },
  {
    rank: 13,
    product: "JanitorAl",
    category: "Al Character Generat",
    visits: "67.77M",
    change: "47.82%",
  },
  {
    rank: 14,
    product: "Claude",
    category: "Al ChatBots",
    visits: "66.31M",
    change: "-0.96%",
  },
  {
    rank: 15,
    product: "百度文库 AI 功能",
    category: "Al Writer Generator",
    visits: "60.63M",
    change: "-7.60%",
  },
  {
    rank: 16,
    product: "Remove.bg",
    category: "Al Image Editor",
    visits: "58.92M",
    change: "-8.30%",
  },
  {
    rank: 17,
    product: "Grammarly",
    category: "Al Writer Generator",
    visits: "58.47M",
    change: "-17.70%",
  },
  {
    rank: 18,
    product: "Quillbot Paraphraser",
    category: "Al Paraphrasing Tool",
    visits: "54.06M",
    change: "-18.37%",
  },
  {
    rank: 19,
    product: "360AI搜索",
    category: "Al Search Engine",
    visits: "51.34M",
    change: "0.71%",
  },
  {
    rank: 20,
    product: "Poe",
    category: "Al ChatBots",
    visits: "45.08M",
    change: "-12.25%",
  },
  {
    rank: 21,
    product: "Khanmigo",
    category: "Al Tools for Education",
    visits: "41.4M",
    change: "-13.99%",
  },
  {
    rank: 22,
    product: "GPT3 Playground",
    category: "Al Code assistant",
    visits: "40.54M",
    change: "-7.04%",
  },
  {
    rank: 23,
    product: "LINER AI",
    category: "Browser Copilot",
    visits: "35.48M",
    change: "-48.88%",
  },
  {
    rank: 24,
    product: "Feedly",
    category: "Al Research Tools",
    visits: "31.5M",
    change: "-7.31%",
  },
  {
    rank: 25,
    product: "Miro",
    category: "Productivity",
    visits: "29.37M",
    change: "-7.77%",
  },
  {
    rank: 26,
    product: "Civitai",
    category: "Model Training & Dep",
    visits: "27.36M",
    change: "4.86%",
  },
  {
    rank: 27,
    product: "天工AI(昆仑万维)",
    category: "Al ChatBots",
    visits: "27.24M",
    change: "59.37%",
  },
  {
    rank: 28,
    product: "SpicyChat Al",
    category: "Al Character Generat",
    visits: "25.79M",
    change: "-5.84%",
  },
  {
    rank: 29,
    product: "CheggMate",
    category: "Al Tools for Education",
    visits: "24.45M",
    change: "-29.82%",
  },
  {
    rank: 30,
    product: "Beacons AI 2.0",
    category: "Al Marketing Tools",
    visits: "24.42M",
    change: "2.85%",
  },
  {
    rank: 31,
    product: "Kimi(月之暗面)",
    category: "Al ChatBots",
    visits: "23.21M",
    change: "0.80%",
  },
  {
    rank: 32,
    product: "Eleven Labs",
    category: "Text to Speech",
    visits: "23.09M",
    change: "4.37%",
  },
  {
    rank: 33,
    product: "Huggingface",
    category: "Model Training & Dep",
    visits: "21.68M",
    change: "-4.86%",
  },
  {
    rank: 34,
    product: "prolific.com",
    category: "Model Training",
    visits: "19.64M",
    change: "8.08%",
  },
  {
    rank: 35,
    product: "Loom",
    category: "Al Video Generators",
    visits: "19.29M",
    change: "-2.76%",
  },
  {
    rank: 36,
    product: "Luma Al",
    category: "Al Video Generators",
    visits: "19.11M",
    change: "1252.21%",
  },
  {
    rank: 37,
    product: "Google Bard",
    category: "Al ChatBots",
    visits: "18.95M",
    change: "-24.21%",
  },
  {
    rank: 38,
    product: "CrushOn",
    category: "Al Character Generat",
    visits: "18.77M",
    change: "5.22%",
  },
  {
    rank: 39,
    product: "Candy.ai",
    category: "Al Character Generat",
    visits: "18.46M",
    change: "27.22%",
  },
  {
    rank: 40,
    product: "Leonardo.Ai",
    category: "Al Image Generator",
    visits: "17.37M",
    change: "-2.73%",
  },
  {
    rank: 41,
    product: "Midjourney",
    category: "Al Image Generator",
    visits: "17.17M",
    change: "-11.17%",
  },
  {
    rank: 42,
    product: "Yodayo",
    category: "Al Image Generator",
    visits: "16.83M",
    change: "-4.72%",
  },
  {
    rank: 43,
    product: "百度文心一言",
    category: "Al ChatBots",
    visits: "16.76M",
    change: "-6.58%",
  },
  {
    rank: 44,
    product: "Prezi",
    category: "Al Presentation Make",
    visits: "14.88M",
    change: "-26.56%",
  },
  {
    rank: 45,
    product: "Mailchimp",
    category: "Al Email Assistants",
    visits: "14.69M",
    change: "-6.93%",
  },
  {
    rank: 46,
    product: "Fotor",
    category: "Al Image Editor",
    visits: "14.44M",
    change: "-9.51%",
  },
  {
    rank: 47,
    product: "Cutout Pro",
    category: "Al Image Enhancer",
    visits: "14.4M",
    change: "-8.40%",
  },
  {
    rank: 48,
    product: "Viggle",
    category: "Al Video Generators",
    visits: "14.4M",
    change: "122.93%",
  },
  {
    rank: 49,
    product: "Photoroom",
    category: "Al Image Editor",
    visits: "14.19M",
    change: "-2.86%",
  },
  {
    rank: 50,
    product: "Gamma",
    category: "Al Presentation Make",
    visits: "13.93M",
    change: "-14.15%",
  },
  {
    rank: 51,
    product: "Veed.io",
    category: "Al Video Editing",
    visits: "13.71M",
    change: "0.84%",
  },
  {
    rank: 52,
    product: "Pixlr",
    category: "Al Image Editor",
    visits: "13.19M",
    change: "-1.00%",
  },
  {
    rank: 53,
    product: "Turnitin",
    category: "Al Tools for Education",
    visits: "11.85M",
    change: "-30.00%",
  },
  {
    rank: 54,
    product: "Unity",
    category: "Al Game",
    visits: "11.36M",
    change: "-10.17%",
  },
  {
    rank: 55,
    product: "秘塔AI搜索",
    category: "AI Search Engine",
    visits: "10.96M",
    change: "-26.71%",
  },
  {
    rank: 56,
    product: "kaggle",
    category: "AI Code Assistant",
    visits: "10.84M",
    change: "-14.08%",
  },
  {
    rank: 57,
    product: "AI Time Machine",
    category: "AI Avatar Generators",
    visits: "10.66M",
    change: "-3.29%",
  },
  {
    rank: 58,
    product: "LanguageTool",
    category: "AI Writer Generator",
    visits: "10.65M",
    change: "-12.69%",
  },
  {
    rank: 59,
    product: "webflow",
    category: "AI Build Website",
    visits: "9.82M",
    change: "-5.23%",
  },
  {
    rank: 60,
    product: "DeepAI",
    category: "AI ChatBots",
    visits: "9.74M",
    change: "-15.29%",
  },
  {
    rank: 61,
    product: "ClipChamp",
    category: "AI Video Editing",
    visits: "9.72M",
    change: "-7.06%",
  },
  {
    rank: 62,
    product: "You",
    category: "AI Search Engine",
    visits: "9.65M",
    change: "-16.34%",
  },
  {
    rank: 63,
    product: "SeaArt",
    category: "AI Image Generator",
    visits: "9.55M",
    change: "1.86%",
  },
  {
    rank: 64,
    product: "Adobe Firefly",
    category: "AI Design Tool",
    visits: "9.53M",
    change: "4.83%",
  },
  {
    rank: 65,
    product: "PixAI.Art",
    category: "AI Image Generator",
    visits: "9.35M",
    change: "7.23%",
  },
  {
    rank: 66,
    product: "PLAN by Ixigo",
    category: "AI Travel Planner",
    visits: "9.34M",
    change: "-10.97%",
  },
  {
    rank: 67,
    product: "Udio",
    category: "AI Music Generator",
    visits: "9.32M",
    change: "-44.42%",
  },
  {
    rank: 68,
    product: "ZeroGPT",
    category: "AI Content Detector",
    visits: "9.29M",
    change: "-12.17%",
  },
  {
    rank: 69,
    product: "InVideo",
    category: "AI Video Editing",
    visits: "9.25M",
    change: "20.34%",
  },
  {
    rank: 70,
    product: "slidesgo",
    category: "AI Presentation Maker",
    visits: "9.25M",
    change: "-29.97%",
  },
  {
    rank: 71,
    product: "Turo",
    category: "AI Travel Planner",
    visits: "9.23M",
    change: "6.72%",
  },
  {
    rank: 72,
    product: "CF Spark",
    category: "AI Design Tool",
    visits: "9.07M",
    change: "-2.39%",
  },
  {
    rank: 73,
    product: "Microsoft Designer",
    category: "AI Design Tool",
    visits: "8.99M",
    change: "32.55%",
  },
  {
    rank: 74,
    product: "Zapier",
    category: "Productivity",
    visits: "8.92M",
    change: "-8.70%",
  },
  {
    rank: 75,
    product: "Systeme",
    category: "AI Marketing Tools",
    visits: "8.76M",
    change: "-11.24%",
  },
  {
    rank: 76,
    product: "Vocal Remover",
    category: "AI Voice Generator",
    visits: "8.55M",
    change: "-7.61%",
  },
  {
    rank: 77,
    product: "Pi",
    category: "AI ChatBots",
    visits: "8.51M",
    change: "-8.38%",
  },
  {
    rank: 78,
    product: "Replit",
    category: "AI Code Assistant",
    visits: "8.46M",
    change: "-7.01%",
  },
  {
    rank: 79,
    product: "chub.ai",
    category: "AI Avatar Generators",
    visits: "8.33M",
    change: "4.57%",
  },
  {
    rank: 80,
    product: "PicWish",
    category: "AI Image Editor",
    visits: "8.29M",
    change: "9.45%",
  },
  {
    rank: 81,
    product: "semantic scholar",
    category: "AI Research Tools",
    visits: "8.25M",
    change: "-16.42%",
  },
  {
    rank: 82,
    product: "阿里通义千问",
    category: "AI ChatBots",
    visits: "8.2M",
    change: "0.73%",
  },
  {
    rank: 83,
    product: "GPTZero",
    category: "AI Content Detector",
    visits: "8.15M",
    change: "-32.59%",
  },
  {
    rank: 84,
    product: "obsidian",
    category: "AI Writer Generator",
    visits: "7.82M",
    change: "47.23%",
  },
  {
    rank: 85,
    product: "Vidnoz AI",
    category: "AI Video Generators",
    visits: "7.82M",
    change: "-0.68%",
  },
  {
    rank: 86,
    product: "MaxAI.me",
    category: "Browser Copilot",
    visits: "7.79M",
    change: "-23.93%",
  },
  {
    rank: 87,
    product: "HIX AI",
    category: "AI Writer Generator",
    visits: "7.73M",
    change: "-1.02%",
  },
  {
    rank: 88,
    product: "Pixelcut.ai",
    category: "AI Image Editor",
    visits: "7.54M",
    change: "2.82%",
  },
  {
    rank: 89,
    product: "tipranks",
    category: "AI Finance",
    visits: "7.42M",
    change: "-6.86%",
  },
  {
    rank: 90,
    product: "DataCamp",
    category: "AI Courses",
    visits: "7.41M",
    change: "-1.20%",
  },
  {
    rank: 91,
    product: "gauthmath",
    category: "AI Tools for Education",
    visits: "7.4M",
    change: "-26.70%",
  },
  {
    rank: 92,
    product: "WolframAlpha",
    category: "AI Research Tools",
    visits: "7.26M",
    change: "-19.86%",
  },
  {
    rank: 93,
    product: "ChatPDF",
    category: "ChatPDF",
    visits: "7.17M",
    change: "-24.35%",
  },
  {
    rank: 94,
    product: "Coze",
    category: "AI ChatBots",
    visits: "6.88M",
    change: "4.42%",
  },
  {
    rank: 95,
    product: "NovelAI",
    category: "AI Story Generator",
    visits: "6.87M",
    change: "-5.67%",
  },
  {
    rank: 96,
    product: "ai-novel",
    category: "AI Story Generator",
    visits: "6.68M",
    change: "-22.20%",
  },
  {
    rank: 97,
    product: "Openart",
    category: "AI Image Generator",
    visits: "6.61M",
    change: "7.44%",
  },
  {
    rank: 98,
    product: "Speechify",
    category: "Text to Speech",
    visits: "6.34M",
    change: "-8.70%",
  },
  {
    rank: 99,
    product: "抖音豆包",
    category: "AI ChatBots",
    visits: "6.31M",
    change: "18.11%",
  },
  {
    rank: 100,
    product: "Opus Clip AI",
    category: "AI Video Editing",
    visits: "6.28M",
    change: "5.60%",
  },
]

export const chinaAiProductTop50202406 = [
  {
    rank: 1,
    product: "百度文库 AI 功能",
    category: "AI Writer Generator",
    visits: "60.63M",
    change: "-7.60%",
  },
  {
    rank: 2,
    product: "360AI搜索",
    category: "AI Search Engine",
    visits: "51.34M",
    change: "0.71%",
  },
  {
    rank: 3,
    product: "天工AI(昆仑万维)",
    category: "AI ChatBots",
    visits: "27.24M",
    change: "59.37%",
  },
  {
    rank: 4,
    product: "Kimi(月之暗面)",
    category: "AI ChatBots",
    visits: "23.21M",
    change: "0.80%",
  },
  {
    rank: 5,
    product: "百度文心一言",
    category: "AI ChatBots",
    visits: "16.76M",
    change: "-6.58%",
  },
  {
    rank: 6,
    product: "秘塔AI搜索",
    category: "AI Search Engine",
    visits: "10.96M",
    change: "-26.71%",
  },
  {
    rank: 7,
    product: "阿里通义千问",
    category: "AI ChatBots",
    visits: "8.2M",
    change: "0.73%",
  },
  {
    rank: 8,
    product: "抖音豆包",
    category: "AI ChatBots",
    visits: "6.31M",
    change: "18.11%",
  },
  {
    rank: 9,
    product: "AiPPT.cn",
    category: "AI Presentation Maker",
    visits: "5.5M",
    change: "12.93%",
  },
  {
    rank: 10,
    product: "C知道",
    category: "AI Search Engine",
    visits: "5.24M",
    change: "-22.05%",
  },
  {
    rank: 11,
    product: "美图设计室",
    category: "AI Design Tool",
    visits: "3.87M",
    change: "5.25%",
  },
  {
    rank: 12,
    product: "清华智谱清言",
    category: "AI ChatBots",
    visits: "3.67M",
    change: "-11.11%",
  },
  {
    rank: 13,
    product: "讯飞星火",
    category: "AI ChatBots",
    visits: "2.75M",
    change: "-1.86%",
  },
  {
    rank: 14,
    product: "liblib.art",
    category: "Model Training & Deployment",
    visits: "2.56M",
    change: "5.80%",
  },
  {
    rank: 15,
    product: "稿定AI",
    category: "AI Design Tool",
    visits: "2.54M",
    change: "-7.03%",
  },
  {
    rank: 16,
    product: "Coze",
    category: "AI ChatBots",
    visits: "2.52M",
    change: "1.04%",
  },
  {
    rank: 17,
    product: "墨刀AI",
    category: "AI Design Tool",
    visits: "2.09M",
    change: "15.22%",
  },
  {
    rank: 18,
    product: "沉浸式翻译",
    category: "AI Translate Tools",
    visits: "2.02M",
    change: "0.98%",
  },
  {
    rank: 19,
    product: "火山方舟",
    category: "Model Training & Deployment",
    visits: "1.94M",
    change: "-53.66%",
  },
  {
    rank: 20,
    product: "DeepSeek",
    category: "AI ChatBots",
    visits: "1.9M",
    change: "36.86%",
  },
  {
    rank: 21,
    product: "ProcessOn",
    category: "AI Mind Map Generator",
    visits: "1.71M",
    change: "-25.92%",
  },
  {
    rank: 22,
    product: "魔音工坊",
    category: "AI Audio Editing Tools",
    visits: "1.67M",
    change: "-17.11%",
  },
  {
    rank: 23,
    product: "PixVerse",
    category: "AI Video Generators",
    visits: "1.47M",
    change: "-17.81%",
  },
  {
    rank: 24,
    product: "无限画",
    category: "AI Image Generator",
    visits: "1.42M",
    change: "-8.41%",
  },
  {
    rank: 25,
    product: "ai-bot",
    category: "AI Navigation Site",
    visits: "1.25M",
    change: "11.86%",
  },
  {
    rank: 26,
    product: "同花顺问财",
    category: "AI Finance",
    visits: "1.2M",
    change: "-22.52%",
  },
  {
    rank: 27,
    product: "魔搭社区-阿里达摩院",
    category: "Model Training & Deployment",
    visits: "1.09M",
    change: "10.26%",
  },
  {
    rank: 28,
    product: "MasterGo AI",
    category: "AI Design Tool",
    visits: "1.06M",
    change: "-8.58%",
  },
  {
    rank: 29,
    product: "即时AI",
    category: "AI Design Tool",
    visits: "1.05M",
    change: "-13.02%",
  },
  {
    rank: 30,
    product: "创客贴AI",
    category: "AI Design Tool",
    visits: "935.56K",
    change: "-8.35%",
  },
  {
    rank: 31,
    product: "百度Chat",
    category: "AI ChatBots",
    visits: "930.03K",
    change: "-10.32%",
  },
  {
    rank: 32,
    product: "即梦AI(剪映)",
    category: "AI Image Generator",
    visits: "836.76K",
    change: "395.21%",
  },
  {
    rank: 33,
    product: "可灵AI(快手)",
    category: "AI Video Generators",
    visits: "811.29K",
    change: "0.00%",
  },
  {
    rank: 34,
    product: "海螺AI",
    category: "AI ChatBots",
    visits: "726.76K",
    change: "-12.90%",
  },
  {
    rank: 35,
    product: "提示工程指南",
    category: "AI Prompt Generator",
    visits: "718.38K",
    change: "-21.61%",
  },
  {
    rank: 36,
    product: "讯飞听见",
    category: "AI Transcription Software",
    visits: "697.91K",
    change: "7.86%",
  },
  {
    rank: 37,
    product: "博思AI白板",
    category: "AI Presentation Maker",
    visits: "682.96K",
    change: "-23.72%",
  },
  {
    rank: 38,
    product: "360苏打办公",
    category: "Productivity",
    visits: "647.23K",
    change: "5.13%",
  },
  {
    rank: 39,
    product: "亿图脑图",
    category: "AI Mind Map Generator",
    visits: "632.85K",
    change: "4.46%",
  },
  {
    rank: 40,
    product: "标小智Logo生成",
    category: "AI Image Generator",
    visits: "624.06K",
    change: "-7.70%",
  },
  {
    rank: 41,
    product: "腾讯元宝",
    category: "AI ChatBots",
    visits: "593.94K",
    change: "1093.07%",
  },
  {
    rank: 42,
    product: "秘塔写作猫",
    category: "AI Writer Generator",
    visits: "560.28K",
    change: "-23.73%",
  },
  {
    rank: 43,
    product: "Pixso AI",
    category: "Al Design Tool",
    visits: "551.17K",
    change: "-8.38%",
  },
  {
    rank: 44,
    product: "5118 SEO",
    category: "AI Writer Generator",
    visits: "497.14K",
    change: "-4.94%",
  },
  {
    rank: 45,
    product: "devv.ai",
    category: "AI Search Engine",
    visits: "461.54K",
    change: "-9.26%",
  },
  {
    rank: 46,
    product: "昇思MindSpore",
    category: "AI Code Assistant",
    visits: "446.36K",
    change: "23.34%",
  },
  {
    rank: 47,
    product: "易撰",
    category: "AI Writer Generator",
    visits: "437.29K",
    change: "15.95%",
  },
  {
    rank: 48,
    product: "佐糖",
    category: "AI Image Editor",
    visits: "411.74K",
    change: "-3.38%",
  },
  {
    rank: 49,
    product: "百川智能",
    category: "AI ChatBots",
    visits: "392.59K",
    change: "-24.56%",
  },
  {
    rank: 50,
    product: "阿里通义听悟",
    category: "Productivity",
    visits: "376.48K",
    change: "-10.74%",
  },
]

export const chinaAiSeaProductTop50202406 = [
  {
    rank: 1,
    product: "CrushOn",
    category: "AI Character Generator",
    visits: "18.77M",
    change: "5.22%",
  },
  {
    rank: 2,
    product: "Fotor",
    category: "AI Image Editor",
    visits: "14.44M",
    change: "-9.51%",
  },
  {
    rank: 3,
    product: "Cutout Pro",
    category: "AI Image Enhancer",
    visits: "14.4M",
    change: "-8.40%",
  },
  {
    rank: 4,
    product: "SeaArt",
    category: "AI Image Generator",
    visits: "9.55M",
    change: "1.86%",
  },
  {
    rank: 5,
    product: "PixAI.Art",
    category: "AI Image Generator",
    visits: "9.35M",
    change: "7.23%",
  },
  {
    rank: 6,
    product: "PicWish",
    category: "AI Image Editor",
    visits: "8.29M",
    change: "9.45%",
  },
  {
    rank: 7,
    product: "MaxAI.me",
    category: "Browser Copilot",
    visits: "7.79M",
    change: "-23.93%",
  },
  {
    rank: 8,
    product: "HIX AI",
    category: "AI Writer Generator",
    visits: "7.73M",
    change: "-1.02%",
  },
  {
    rank: 9,
    product: "gauthmath",
    category: "AI Tools for Education",
    visits: "7.4M",
    change: "-26.70%",
  },
  {
    rank: 10,
    product: "Coze",
    category: "AI ChatBots",
    visits: "6.88M",
    change: "4.42%",
  },
  {
    rank: 11,
    product: "Openart",
    category: "AI Image Generator",
    visits: "6.61M",
    change: "7.44%",
  },
  {
    rank: 12,
    product: "Opus Clip AI",
    category: "AI Video Editing",
    visits: "6.28M",
    change: "5.60%",
  },
  {
    rank: 13,
    product: "Monica",
    category: "Browser Copilot",
    visits: "5.83M",
    change: "-6.77%",
  },
  {
    rank: 14,
    product: "Media.io",
    category: "AI Video Editing",
    visits: "5.56M",
    change: "-8.82%",
  },
  {
    rank: 15,
    product: "Notta",
    category: "AI Meeting Assistant",
    visits: "4.56M",
    change: "-11.18%",
  },
  {
    rank: 16,
    product: "flowGPT",
    category: "AI Prompt Generator",
    visits: "4.46M",
    change: "-22.09%",
  },
  {
    rank: 17,
    product: "Toolify",
    category: "AI Navigation Site",
    visits: "3.98M",
    change: "-6.66%",
  },
  {
    rank: 18,
    product: "HeyGen",
    category: "AI Video Generators",
    visits: "3.88M",
    change: "-1.02%",
  },
  {
    rank: 19,
    product: "ciciai",
    category: "AI ChatBots",
    visits: "2.78M",
    change: "-12.36%",
  },
  {
    rank: 20,
    product: "Joyland",
    category: "AI Character Generator",
    visits: "2.75M",
    change: "70.97%",
  },
  {
    rank: 21,
    product: "Filmora",
    category: "AI Video Editing",
    visits: "2.58M",
    change: "-7.46%",
  },
  {
    rank: 22,
    product: "Haiper",
    category: "AI Video Generators",
    visits: "2.33M",
    change: "-1.19%",
  },
  {
    rank: 23,
    product: "Talkie",
    category: "AI ChatBots",
    visits: "2.32M",
    change: "76.88%",
  },
  {
    rank: 24,
    product: "ZMO.ai",
    category: "AI Image Enhancer",
    visits: "2.24M",
    change: "-15.25%",
  },
  {
    rank: 25,
    product: "Pika Art",
    category: "AI Video Generators",
    visits: "1.64M",
    change: "-26.06%",
  },
  {
    rank: 26,
    product: "stablediffusionweb",
    category: "AI Image Generator",
    visits: "1.61M",
    change: "-0.93%",
  },
  {
    rank: 27,
    product: "Anakin",
    category: "AI Build Application",
    visits: "1.58M",
    change: "-6.39%",
  },
  {
    rank: 28,
    product: "Vizard.ai",
    category: "AI Video Editing",
    visits: "1.55M",
    change: "-24.80%",
  },
  {
    rank: 29,
    product: "Akool",
    category: "AI Marketing Tools",
    visits: "1.48M",
    change: "20.22%",
  },
  {
    rank: 30,
    product: "PixVerse",
    category: "AI Video Generators",
    visits: "1.47M",
    change: "-17.81%",
  },
  {
    rank: 31,
    product: "Vivago",
    category: "AI Image Generator",
    visits: "1.18M",
    change: "357.81%",
  },
  {
    rank: 32,
    product: "Videoconverter",
    category: "AI Video Editing",
    visits: "943.43K",
    change: "-7.86%",
  },
  {
    rank: 33,
    product: "Theb.ai",
    category: "AI ChatBots",
    visits: "928.41K",
    change: "-18.07%",
  },
  {
    rank: 34,
    product: "powerdrill.ai",
    category: "Data Analytics",
    visits: "917.63K",
    change: "48.47%",
  },
  {
    rank: 35,
    product: "anybagel",
    category: "AI Character Generator",
    visits: "767.97K",
    change: "82.56%",
  },
  {
    rank: 36,
    product: "Artflow AI",
    category: "AI Story Generator",
    visits: "735.78K",
    change: "-24.40%",
  },
  {
    rank: 37,
    product: "Meshy",
    category: "3D",
    visits: "721.37K",
    change: "3.94%",
  },
  {
    rank: 38,
    product: "virbo",
    category: "AI Recruiting Tools",
    visits: "691.55K",
    change: "235.92%",
  },
  {
    rank: 39,
    product: "finalroundai",
    category: "AI Video Generators",
    visits: "651.4K",
    change: "5.70%",
  },
  {
    rank: 40,
    product: "Thinkany",
    category: "AI Search Engine",
    visits: "645.63K",
    change: "4.04%",
  },
]

export const a16zTopWebAI = [
  {
    rank: 1,
    product: "ChatGPT",
    link: "https://chat.openai.com/",
  },
  {
    rank: 2,
    product: "Gemini",
    link: "https://gemini.google.com/",
  },
  {
    rank: 3,
    product: "Character.AI",
    link: "https://beta.character.ai/",
  },
  {
    rank: 4,
    product: "Liner",
    link: "https://getliner.com/",
  },
  {
    rank: 5,
    product: "QuillBot",
    link: "http://quillbot.com",
  },
  {
    rank: 6,
    product: "Poe",
    link: "http://poe.com/",
  },
  {
    rank: 7,
    product: "Perplexity",
    link: "https://www.perplexity.ai/",
  },
  {
    rank: 8,
    product: "JanitorAI",
    link: "http://janitorai.com/",
  },
  {
    rank: 9,
    product: "Civitai",
    link: "http://civitai.com",
  },
  {
    rank: 10,
    product: "Claude",
    link: "https://claude.ai/",
  },
  {
    rank: 11,
    product: "ElevenLabs",
    link: "https://elevenlabs.io/",
  },
  {
    rank: 12,
    product: "Hugging Face",
    link: "https://huggingface.co/",
  },
  {
    rank: 13,
    product: "Leonardo.AI",
    link: "http://leonardo.ai/",
  },
  {
    rank: 14,
    product: "Midjourney",
    link: "http://midjourney.com",
  },
  {
    rank: 15,
    product: "SpicyChat",
    link: "http://spicychat.ai/",
  },
  {
    rank: 16,
    product: "Gamma",
    link: "https://gamma.app/",
  },
  {
    rank: 17,
    product: "CrushOn AI",
    link: "http://crushon.ai/",
  },
  {
    rank: 18,
    product: "Cutout.pro",
    link: "https://www.cutout.pro/",
  },
  {
    rank: 19,
    product: "Pixlr",
    link: "http://pixlr.com",
  },
  {
    rank: 20,
    product: "Veed.io",
    link: "https://www.veed.io/",
  },
  {
    rank: 21,
    product: "PhotoRoom",
    link: "http://photoroom.com/",
  },
  {
    rank: 22,
    product: "Yodayo",
    link: "http://yodayo.com/",
  },
  {
    rank: 23,
    product: "Clipchamp",
    link: "http://clipchamp.com/",
  },
  {
    rank: 24,
    product: "Runway",
    link: "http://runwayml.com",
  },
  {
    rank: 25,
    product: "You.com",
    link: "https://you.com/",
  },
  {
    rank: 26,
    product: "DeepAI",
    link: "http://deepai.org/",
  },
  {
    rank: 27,
    product: "Eightify",
    link: "https://eightify.app/",
  },
  {
    rank: 28,
    product: "Candy.ai",
    link: "https://candy.ai/",
  },
  {
    rank: 29,
    product: "NightCafe",
    link: "https://creator.nightcafe.studio/",
  },
  {
    rank: 30,
    product: "VocalRemover",
    link: "https://vocalremover.org/",
  },
  {
    rank: 31,
    product: "Pixai",
    link: "https://pixai.art/",
  },
  {
    rank: 32,
    product: "Ideogram",
    link: "http://ideogram.ai/",
  },
  {
    rank: 33,
    product: "InVideo",
    link: "http://invideo.io/",
  },
  {
    rank: 34,
    product: "Replicate",
    link: "https://replicate.com/",
  },
  {
    rank: 35,
    product: "Playground",
    link: "http://playgroundai.com/",
  },
  {
    rank: 36,
    product: "Suno",
    link: "https://www.suno.ai/",
  },
  {
    rank: 37,
    product: "Chub.ai",
    link: "http://chub.ai/",
  },
  {
    rank: 38,
    product: "Speechify",
    link: "http://speechify.com/",
  },
  {
    rank: 39,
    product: "Phind",
    link: "http://phind.com/",
  },
  {
    rank: 40,
    product: "NovelAI",
    link: "http://novelai.net/",
  },
  {
    rank: 41,
    product: "MaxAI",
    link: "http://maxai.me/",
  },
  {
    rank: 42,
    product: "Craiyon",
    link: "http://craiyon.com/",
  },
  {
    rank: 43,
    product: "OpusClip",
    link: "http://opus.pro",
  },
  {
    rank: 44,
    product: "Blackbox AI",
    link: "https://www.blackbox.ai/",
  },
  {
    rank: 45,
    product: "ChatPDF",
    link: "https://www.chatpdf.com/",
  },
  {
    rank: 46,
    product: "Pixelcut",
    link: "http://pixelcut.ai/",
  },
  {
    rank: 47,
    product: "Vectorizer.AI",
    link: "https://vectorizer.ai/",
  },
  {
    rank: 48,
    product: "DreamGF",
    link: "https://dreamgf.ai/",
  },
  {
    rank: 49,
    product: "Photomyne",
    link: "https://photomyne.com/",
  },
  {
    rank: 50,
    product: "Otter.ai",
    link: "http://otter.ai/",
  },
]

export const a16zTopAppAI = [
  {
    rank: 1,
    product: "ChatGPT",
    link: "https://apps.apple.com/us/app/chatgpt/id6448311069",
  },
  {
    rank: 2,
    product: "Microsoft Edge",
    link: "https://apps.apple.com/us/app/microsoft-edge-ai-browser/id1288723196",
  },
  {
    rank: 3,
    product: "Photomath",
    link: "https://apps.apple.com/us/app/photomath/id919087726",
  },
  {
    rank: 4,
    product: "Bing",
    link: "https://apps.apple.com/us/app/bing-chat-with-ai-gpt-4/id345323231",
  },
  {
    rank: 5,
    product: "Remini",
    link: "https://apps.apple.com/us/app/remini-ai-photo-enhancer/id1470373330",
  },
  {
    rank: 6,
    product: "Brainly",
    link: "https://apps.apple.com/us/app/brainly-ai-homework-helper/id745089947",
  },
  {
    rank: 7,
    product: "NOVA",
    link: "https://apps.apple.com/us/app/ai-chatbot-nova/id1669007652",
  },
  {
    rank: 8,
    product: "Chat & Ask AI",
    link: "https://apps.apple.com/us/app/chat-ask-ai-by-codeway/id1668787639",
  },
  {
    rank: 9,
    product: "Facemoji",
    link: "https://apps.apple.com/us/app/facemoji-ai-emoji-keyboard/id1103138272",
  },
  {
    rank: 10,
    product: "EPIK",
    link: "https://apps.apple.com/us/app/epik-ai-photo-video-editor/id1577705074",
  },
  {
    rank: 11,
    product: "Photoroom",
    link: "https://apps.apple.com/us/app/photoroom-ai-photo-editor/id1455009060",
  },
  {
    rank: 12,
    product: "Remove It",
    link: "https://play.google.com/store/apps/details?id=com.vyroai.objectremover&hl=en_US",
  },
  {
    rank: 13,
    product: "Evoke AI",
    link: "https://apps.apple.com/us/app/ai-photo-enhancer-evoke/id6450504740",
  },
  {
    rank: 14,
    product: "AI Chatbot: AI Chat Smith 4",
    link: "https://apps.apple.com/us/app/ai-chatbot-ai-chat-smith-4/id1559479889",
  },
  {
    rank: 15,
    product: "ChatBot",
    link: "https://chatbot-ai-chat.en.softonic.com/",
  },
  {
    rank: 16,
    product: "character.ai",
    link: "https://apps.apple.com/us/app/character-ai-ai-powered-chat/id1671705818",
  },
  {
    rank: 17,
    product: "AI Mirror",
    link: "https://apps.apple.com/us/app/ai-mirror-ai-art-photo-editor/id6444888896",
  },
  {
    rank: 18,
    product: "ChatOn",
    link: "https://apps.apple.com/us/app/chaton-ai-chat-bot-assistant/id1661308505",
  },
  {
    rank: 19,
    product: "QANDA",
    link: "https://apps.apple.com/us/app/qanda-instant-math-helper/id1270676408",
  },
  {
    rank: 20,
    product: "Face Dance",
    link: "https://apps.apple.com/us/app/face-dance-ai-photo-animator/id1589749730",
  },
  {
    rank: 21,
    product: "Beat.ly",
    link: "https://play.google.com/store/apps/details?id=vinkle.video.editor",
  },
  {
    rank: 22,
    product: "Photo AI",
    link: "https://apps.apple.com/us/app/photoai-ai-photo-enhancer/id1590124720",
  },
  {
    rank: 23,
    product: "Hypic",
    link: "https://apps.apple.com/us/app/hypic-photo-editor-ai-art/id1644042837",
  },
  {
    rank: 24,
    product: "Al Quran",
    link: "https://apps.apple.com/us/app/al-quran-tafsir-by-word/id1437038111",
  },
  {
    rank: 25,
    product: "ArtMind",
    link: "https://apps.apple.com/us/app/artmind/id6477348273",
  },
  {
    rank: 26,
    product: "SnapEdit",
    link: "https://play.google.com/store/apps/details?id=snapedit.app.remove",
  },
  {
    rank: 27,
    product: "Imagine",
    link: "https://apps.apple.com/us/app/imagine-ai-art-generator/id1664121419",
  },
  {
    rank: 28,
    product: "Question AI",
    link: "https://apps.apple.com/us/app/question-ai-ai-math-calculator/id6449486871",
  },
  {
    rank: 29,
    product: "ChatBox",
    link: "https://apps.apple.com/us/app/chatbox-ask-ai-chatbot/id6447763703",
  },
  {
    rank: 30,
    product: "DaVinci",
    link: "https://apps.apple.com/us/app/davinci-ai-image-generator/id1630366866",
  },
  {
    rank: 31,
    product: "Bobble AI",
    link: "https://apps.apple.com/us/app/bobble-ai-keyboard-assistant/id972432964",
  },
  {
    rank: 32,
    product: "reface",
    link: "https://apps.apple.com/us/app/reface-ai-photo-generator/id1488782587?ppid=eb3a176a-5e0e-42f2-99f5-78428b29eace",
  },
  {
    rank: 33,
    product: "PhotoApp",
    link: "https://apps.apple.com/us/app/photoapp-ai-photo-enhancer/id1596089614",
  },
  {
    rank: 34,
    product: "Prequel",
    link: "https://apps.apple.com/us/app/prequel-photo-video-editor/id1325756279",
  },
  {
    rank: 35,
    product: "Mathway",
    link: "https://apps.apple.com/us/app/mathway-math-problem-solver/id467329677",
  },
  {
    rank: 36,
    product: "Poly.AI",
    link: "https://apps.apple.com/us/app/poly-ai-create-ai-chat-bot/id6449190344",
  },
  {
    rank: 37,
    product: "Genie",
    link: "https://apps.apple.com/us/app/genie-ai-chatbot-keyboard/id1658377526",
  },
  {
    rank: 38,
    product: "Photoleap",
    link: "https://apps.apple.com/us/app/photoleap-ai-art-photo-editor/id1191337894",
  },
  {
    rank: 39,
    product: "Wonder",
    link: "https://apps.apple.com/us/app/wonder-ai-art-generator/id1621278575",
  },
  {
    rank: 40,
    product: "Copilot",
    link: "https://apps.apple.com/us/app/microsoft-copilot/id6472538445",
  },
  {
    rank: 41,
    product: "Chat AI",
    link: "https://play.google.com/store/apps/details?id=com.ai.chat.bot.aichat",
  },
  {
    rank: 42,
    product: "ELSA",
    link: "https://apps.apple.com/us/app/elsa-speak-english-learning/id1083804886",
  },
  {
    rank: 43,
    product: "AI ARTA",
    link: "https://apps.apple.com/us/app/arta-ai-photo-generator-al-art/id1642969698",
  },
  {
    rank: 44,
    product: "AI Chat",
    link: "https://apps.apple.com/us/app/ai-chat-assistant-chatbot/id1667518571",
  },
  {
    rank: 45,
    product: "Revive",
    link: "https://apps.apple.com/us/app/revive-ai-photo-dance-maker/id1616862692",
  },
  {
    rank: 46,
    product: "LISA AI",
    link: "https://apps.apple.com/us/app/lisa-ai-retro-wedding-avatar/id6443832829",
  },
  {
    rank: 47,
    product: "PIXELCUT",
    link: "https://apps.apple.com/us/app/pixelcut-ai-photo-editor/id1534785237",
  },
  {
    rank: 48,
    product: "AI Chat - Assistant",
    link: "https://apps.apple.com/us/app/ai-chat-assistant-chatbot/id1667518571",
  },
  {
    rank: 49,
    product: "Poe",
    link: "https://apps.apple.com/us/app/poe-fast-ai-chat/id1640745955",
  },
  {
    rank: 50,
    product: "Replika",
    link: "https://apps.apple.com/us/app/replika-my-ai-friend/id1158555867",
  },
]
