export const rankAllData = [
  {
    rank: 1,
    product_name: "ChatGPT",
    category: "AI ChatBots",
    estimated_visits_april: 1642000,
    change_from_last_month: "2%",
  },
  {
    rank: 2,
    product_name: "NewBing",
    category: "",
    estimated_visits_april: 164800,
    change_from_last_month: "3%",
  },
  {
    rank: 3,
    product_name: "Canva AI",
    category: "绘图设计工具",
    estimated_visits_april: 148700,
    change_from_last_month: "-4%",
  },
  {
    rank: 4,
    product_name: "Google Gemini",
    category: "AI ChatBots",
    estimated_visits_april: 38800,
    change_from_last_month: "-1%",
  },
  {
    rank: 5,
    product_name: "Adobe firefly",
    category: "图像生成",
    estimated_visits_april: 20300,
    change_from_last_month: "-6%",
  },
  {
    rank: 6,
    product_name: "DeepL",
    category: "翻译",
    estimated_visits_april: 26600,
    change_from_last_month: "10%",
  },
  {
    rank: 7,
    product_name: "Character.AI",
    category: "AI ChatBots",
    estimated_visits_april: 12600,
    change_from_last_month: "2%",
  },
  {
    rank: 8,
    product_name: "Notion AI",
    category: "通用写作",
    estimated_visits_april: 9250,
    change_from_last_month: "-2%",
  },
  {
    rank: 9,
    product_name: "ChatGPT",
    category: "AI ChatBots",
    estimated_visits_april: 6400,
    change_from_last_month: "-7%",
  },
  {
    rank: 10,
    product_name: "IShop",
    category: "虚拟陪伴",
    estimated_visits_april: 8800,
    change_from_last_month: "-2%",
  },
  {
    rank: 11,
    product_name: "Top Tech",
    category: "垂直行业",
    estimated_visits_april: 8824,
    change_from_last_month: "2%",
  },
  {
    rank: 12,
    product_name: "figma+jamboard",
    category: "图像编辑",
    estimated_visits_april: 8557,
    change_from_last_month: "2%",
  },
  {
    rank: 13,
    product_name: "Salesforce",
    category: "",
    estimated_visits_april: 8754,
    change_from_last_month: "2%",
  },
  {
    rank: 14,
    product_name: "Pimeyes",
    category: "",
    estimated_visits_april: 7834,
    change_from_last_month: "0%",
  },
  {
    rank: 15,
    product_name: "ChatPDF",
    category: "AI ChatBots",
    estimated_visits_april: 7664,
    change_from_last_month: "8%",
  },
  {
    rank: 16,
    product_name: "Papercup AI",
    category: "图生视频",
    estimated_visits_april: 7408,
    change_from_last_month: "-2%",
  },
  {
    rank: 17,
    product_name: "ChatPDF",
    category: "AI ChatBots",
    estimated_visits_april: 7664,
    change_from_last_month: "8%",
  },
  {
    rank: 18,
    product_name: "Studioxrock",
    category: "图像生成",
    estimated_visits_april: 6674,
    change_from_last_month: "-4%",
  },
  {
    rank: 19,
    product_name: "Skill AI",
    category: "AI ChatBots",
    estimated_visits_april: 6240,
    change_from_last_month: "0%",
  },
  {
    rank: 20,
    product_name: "LINER AI",
    category: "",
    estimated_visits_april: 5900,
    change_from_last_month: "2%",
  },
  {
    rank: 21,
    product_name: "ReImagine",
    category: "",
    estimated_visits_april: 5377,
    change_from_last_month: "-7%",
  },
  {
    rank: 22,
    product_name: "Ontraport",
    category: "",
    estimated_visits_april: 5250,
    change_from_last_month: "-3%",
  },
  {
    rank: 23,
    product_name: "Poe",
    category: "AI ChatBots",
    estimated_visits_april: 4974,
    change_from_last_month: "4%",
  },
  {
    rank: 24,
    product_name: "kmeringo",
    category: "AI ChatBots",
    estimated_visits_april: 4896,
    change_from_last_month: "5%",
  },
  {
    rank: 25,
    product_name: "DeepChat AI",
    category: "AI ChatBots",
    estimated_visits_april: 4624,
    change_from_last_month: "2%",
  },
  {
    rank: 26,
    product_name: "SpicyChat.AI",
    category: "AI ChatBots",
    estimated_visits_april: 4278,
    change_from_last_month: "5%",
  },
  {
    rank: 27,
    product_name: "GPT3 Playground",
    category: "AI ChatBots",
    estimated_visits_april: 4216,
    change_from_last_month: "-7%",
  },
  {
    rank: 28,
    product_name: "figma+jamboard",
    category: "图像编辑",
    estimated_visits_april: 3828,
    change_from_last_month: "2%",
  },
  {
    rank: 29,
    product_name: "Hopscotch",
    category: "",
    estimated_visits_april: 2896,
    change_from_last_month: "7%",
  },
  {
    rank: 30,
    product_name: "Cvat.ai",
    category: "",
    estimated_visits_april: 2380,
    change_from_last_month: "1%",
  },
  {
    rank: 31,
    product_name: "Beacoms AI 2.0",
    category: "AI ChatBots",
    estimated_visits_april: 2117,
    change_from_last_month: "0%",
  },
  {
    rank: 32,
    product_name: "SpicyChat.AI",
    category: "AI ChatBots",
    estimated_visits_april: 2077,
    change_from_last_month: "5%",
  },
  {
    rank: 33,
    product_name: "Reeni",
    category: "",
    estimated_visits_april: 2017,
    change_from_last_month: "0%",
  },
  {
    rank: 34,
    product_name: "Bifrost Labs",
    category: "",
    estimated_visits_april: 1899,
    change_from_last_month: "1%",
  },
  {
    rank: 35,
    product_name: "KarmaKorner.ai",
    category: "AI ChatBots",
    estimated_visits_april: 1839,
    change_from_last_month: "5%",
  },
  {
    rank: 36,
    product_name: "Flowrite",
    category: "AI ChatBots",
    estimated_visits_april: 1798,
    change_from_last_month: "-2%",
  },
  {
    rank: 37,
    product_name: "mailchimp",
    category: "邮件助手",
    estimated_visits_april: 1747,
    change_from_last_month: "-2%",
  },
  {
    rank: 38,
    product_name: "Replai",
    category: "",
    estimated_visits_april: 1748,
    change_from_last_month: "-6%",
  },
  {
    rank: 39,
    product_name: "MidJourney",
    category: "图像生成",
    estimated_visits_april: 1709,
    change_from_last_month: "0%",
  },
  {
    rank: 40,
    product_name: "Lessexx AI",
    category: "AI ChatBots",
    estimated_visits_april: 1643,
    change_from_last_month: "-4%",
  },
  {
    rank: 41,
    product_name: "Cushion",
    category: "视频编辑",
    estimated_visits_april: 1683,
    change_from_last_month: "1%",
  },
  {
    rank: 42,
    product_name: "Gptforresearch.com",
    category: "AI ChatBots",
    estimated_visits_april: 1660,
    change_from_last_month: "0%",
  },
  {
    rank: 43,
    product_name: "Cutout.pro",
    category: "图像生成",
    estimated_visits_april: 1620,
    change_from_last_month: "2%",
  },
  {
    rank: 44,
    product_name: "Yeduo",
    category: "",
    estimated_visits_april: 1590,
    change_from_last_month: "-5%",
  },
  {
    rank: 45,
    product_name: "Fotor",
    category: "",
    estimated_visits_april: 1577,
    change_from_last_month: "-2%",
  },
  {
    rank: 46,
    product_name: "Bifi",
    category: "",
    estimated_visits_april: 1460,
    change_from_last_month: "0%",
  },
  {
    rank: 47,
    product_name: "ssuiteos.com",
    category: "",
    estimated_visits_april: 1473,
    change_from_last_month: "2%",
  },
  {
    rank: 48,
    product_name: "Lensica AI",
    category: "",
    estimated_visits_april: 1420,
    change_from_last_month: "1%",
  },
  {
    rank: 49,
    product_name: "Wendu AI",
    category: "AI ChatBots",
    estimated_visits_april: 1380,
    change_from_last_month: "0%",
  },
  {
    rank: 50,
    product_name: "Replit",
    category: "编程工具",
    estimated_visits_april: 1220,
    change_from_last_month: "1%",
  },
  {
    rank: 51,
    product_name: "Looka.com",
    category: "",
    estimated_visits_april: 1210,
    change_from_last_month: "1%",
  },
  {
    rank: 52,
    product_name: "Picuio.com",
    category: "",
    estimated_visits_april: 1173,
    change_from_last_month: "1%",
  },
  {
    rank: 53,
    product_name: "Slidego",
    category: "",
    estimated_visits_april: 1120,
    change_from_last_month: "-4%",
  },
  {
    rank: 54,
    product_name: "Sidepop",
    category: "",
    estimated_visits_april: 1074,
    change_from_last_month: "1%",
  },
  {
    rank: 55,
    product_name: "RoboFlow",
    category: "AI ChatBots",
    estimated_visits_april: 1065,
    change_from_last_month: "2%",
  },
  {
    rank: 56,
    product_name: "gfg",
    category: "AI ChatBots",
    estimated_visits_april: 1034,
    change_from_last_month: "2%",
  },
  {
    rank: 57,
    product_name: "ZeroGPT",
    category: "AI ChatBots",
    estimated_visits_april: 1032,
    change_from_last_month: "4%",
  },
  {
    rank: 58,
    product_name: "Spacehally",
    category: "AI ChatBots",
    estimated_visits_april: 1020,
    change_from_last_month: "0%",
  },
  {
    rank: 59,
    product_name: "DeepAi",
    category: "AI ChatBots",
    estimated_visits_april: 1013,
    change_from_last_month: "1%",
  },
  {
    rank: 60,
    product_name: "WembaAI",
    category: "",
    estimated_visits_april: 1009,
    change_from_last_month: "6%",
  },
  {
    rank: 61,
    product_name: "SatChat AI",
    category: "AI ChatBots",
    estimated_visits_april: 1002,
    change_from_last_month: "-5%",
  },
  {
    rank: 62,
    product_name: "GC Spark",
    category: "",
    estimated_visits_april: 987,
    change_from_last_month: "-7%",
  },
  {
    rank: 63,
    product_name: "PLAN by Indigo",
    category: "AI ChatBots",
    estimated_visits_april: 942,
    change_from_last_month: "-2%",
  },
  {
    rank: 64,
    product_name: "Replai",
    category: "",
    estimated_visits_april: 918,
    change_from_last_month: "1%",
  },
  {
    rank: 65,
    product_name: "Semantic Scholar",
    category: "",
    estimated_visits_april: 917,
    change_from_last_month: "-7%",
  },
  {
    rank: 66,
    product_name: "Replai",
    category: "",
    estimated_visits_april: 879,
    change_from_last_month: "-4%",
  },
  {
    rank: 67,
    product_name: "Semantic Scholar",
    category: "",
    estimated_visits_april: 860,
    change_from_last_month: "-7%",
  },
  {
    rank: 68,
    product_name: "Pitch",
    category: "",
    estimated_visits_april: 842,
    change_from_last_month: "1%",
  },
  {
    rank: 69,
    product_name: "Storypitchgenius.com",
    category: "",
    estimated_visits_april: 816,
    change_from_last_month: "-2%",
  },
  {
    rank: 70,
    product_name: "Ideaopra.com",
    category: "",
    estimated_visits_april: 806,
    change_from_last_month: "1%",
  },
  {
    rank: 71,
    product_name: "Pin Novel",
    category: "AI ChatBots",
    estimated_visits_april: 794,
    change_from_last_month: "-4%",
  },
  {
    rank: 72,
    product_name: "PoeChat AI",
    category: "AI ChatBots",
    estimated_visits_april: 789,
    change_from_last_month: "-5%",
  },
  {
    rank: 73,
    product_name: "Ideaopra.com",
    category: "",
    estimated_visits_april: 778,
    change_from_last_month: "-12%",
  },
  {
    rank: 74,
    product_name: "PDFCoCo",
    category: "AI ChatBots",
    estimated_visits_april: 749,
    change_from_last_month: "1%",
  },
  {
    rank: 75,
    product_name: "Pin Novel",
    category: "AI ChatBots",
    estimated_visits_april: 744,
    change_from_last_month: "0%",
  },
  {
    rank: 76,
    product_name: "Replit",
    category: "编程工具",
    estimated_visits_april: 719,
    change_from_last_month: "-2%",
  },
  {
    rank: 77,
    product_name: "Spacehally",
    category: "AI ChatBots",
    estimated_visits_april: 702,
    change_from_last_month: "0%",
  },
  {
    rank: 78,
    product_name: "Pin Novel",
    category: "AI ChatBots",
    estimated_visits_april: 677,
    change_from_last_month: "1%",
  },
  {
    rank: 79,
    product_name: "Replit",
    category: "编程工具",
    estimated_visits_april: 671,
    change_from_last_month: "-7%",
  },
  {
    rank: 80,
    product_name: "Slidego",
    category: "",
    estimated_visits_april: 662,
    change_from_last_month: "1%",
  },
  {
    rank: 81,
    product_name: "Semantic Scholar",
    category: "",
    estimated_visits_april: 641,
    change_from_last_month: "-4%",
  },
  {
    rank: 82,
    product_name: "Pitch",
    category: "",
    estimated_visits_april: 624,
    change_from_last_month: "1%",
  },
  {
    rank: 83,
    product_name: "Storypitchgenius.com",
    category: "",
    estimated_visits_april: 610,
    change_from_last_month: "-6%",
  },
  {
    rank: 84,
    product_name: "Ideaopra.com",
    category: "",
    estimated_visits_april: 589,
    change_from_last_month: "-3%",
  },
  {
    rank: 85,
    product_name: "Pin Novel",
    category: "AI ChatBots",
    estimated_visits_april: 576,
    change_from_last_month: "-6%",
  },
  {
    rank: 86,
    product_name: "PoeChat AI",
    category: "AI ChatBots",
    estimated_visits_april: 562,
    change_from_last_month: "1%",
  },
  {
    rank: 87,
    product_name: "Ideaopra.com",
    category: "",
    estimated_visits_april: 554,
    change_from_last_month: "0%",
  },
  {
    rank: 88,
    product_name: "PDFCoCo",
    category: "AI ChatBots",
    estimated_visits_april: 544,
    change_from_last_month: "1%",
  },
  {
    rank: 89,
    product_name: "Pin Novel",
    category: "AI ChatBots",
    estimated_visits_april: 531,
    change_from_last_month: "-7%",
  },
  {
    rank: 90,
    product_name: "Replit",
    category: "编程工具",
    estimated_visits_april: 512,
    change_from_last_month: "-2%",
  },
  {
    rank: 91,
    product_name: "Replit",
    category: "编程工具",
    estimated_visits_april: 497,
    change_from_last_month: "-4%",
  },
  {
    rank: 92,
    product_name: "Semantic Scholar",
    category: "",
    estimated_visits_april: 479,
    change_from_last_month: "-2%",
  },
  {
    rank: 93,
    product_name: "Pitch",
    category: "",
    estimated_visits_april: 460,
    change_from_last_month: "1%",
  },
  {
    rank: 94,
    product_name: "Ideaopra.com",
    category: "",
    estimated_visits_april: 448,
    change_from_last_month: "-5%",
  },
  {
    rank: 95,
    product_name: "Pin Novel",
    category: "AI ChatBots",
    estimated_visits_april: 437,
    change_from_last_month: "1%",
  },
  {
    rank: 96,
    product_name: "PoeChat AI",
    category: "AI ChatBots",
    estimated_visits_april: 423,
    change_from_last_month: "0%",
  },
  {
    rank: 97,
    product_name: "Ideaopra.com",
    category: "",
    estimated_visits_april: 410,
    change_from_last_month: "0%",
  },
  {
    rank: 98,
    product_name: "PDFCoCo",
    category: "AI ChatBots",
    estimated_visits_april: 398,
    change_from_last_month: "0%",
  },
  {
    rank: 99,
    product_name: "Pin Novel",
    category: "AI ChatBots",
    estimated_visits_april: 387,
    change_from_last_month: "-1%",
  },
  {
    rank: 100,
    product_name: "Ideaopra.com",
    category: "",
    estimated_visits_april: 370,
    change_from_last_month: "0%",
  },
]
